/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import Tela.TelaAddEstoque;
import Tela.TelaAtualizarEstoque;
import classes.cliente;
import classes.estoque;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistenciaCliente.ClienteDao;
import persistenciaEstoque.EstoqueDao;

/**
 *
 * @author ALUNO
 */
public class TelaConsultaEstoque extends javax.swing.JInternalFrame {

    public static boolean consultae;
    public static boolean attestoque;

    /**
     * Creates new form TelaConsultaEstoque
     */
    public TelaConsultaEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jConsultae = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jctipodeOpcaoDeBusca = new javax.swing.JComboBox<>();
        jTextField1campoBusca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JToggleButton();
        jButtonexcluir = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        JtableSaida = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();

        setTitle("Consulta Estoque");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jctipodeOpcaoDeBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descrição", "ID", "Código" }));
        jctipodeOpcaoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipodeOpcaoDeBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 6, 0, 0);
        jPanel1.add(jctipodeOpcaoDeBusca, gridBagConstraints);

        jTextField1campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1campoBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(jTextField1campoBusca, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 201, 6, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jButtonBuscar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 0);
        jPanel1.add(jButtonBuscar, gridBagConstraints);

        jButtonexcluir.setBackground(new java.awt.Color(255, 51, 0));
        jButtonexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-trash-16.png"))); // NOI18N
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 201, 0, 0);
        jPanel1.add(jButtonexcluir, gridBagConstraints);

        JtableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "ID", "Código", "Qnt. Em Estoque", "Valor/UN", "Estoque Mínimo", "Qtd Em Reserva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableSaidaMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(JtableSaida);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 995;
        gridBagConstraints.ipady = 373;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 8, 0, 6);
        jPanel1.add(jScrollPane, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Voltar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 137, 6, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jButtonVoltar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 137, 0, 0);
        jPanel1.add(jButtonVoltar, gridBagConstraints);

        jConsultae.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jConsultaeLayout = new javax.swing.GroupLayout(jConsultae);
        jConsultae.setLayout(jConsultaeLayout);
        jConsultaeLayout.setHorizontalGroup(
            jConsultaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jConsultaeLayout.setVerticalGroup(
            jConsultaeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jConsultae)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jConsultae)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jctipodeOpcaoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipodeOpcaoDeBuscaActionPerformed
//        if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Código")) {
//            jTextField1campoBusca
//            
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jctipodeOpcaoDeBuscaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            EstoqueDao lista = new EstoqueDao();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();

            ArrayList<estoque> listaEstoque = null;
            listaEstoque = lista.obterPecas();
            String[] vetString = new String[5];
            model.setRowCount(0);
            boolean contem = false;
            for (int i = 0; i < listaEstoque.size(); i++) {

                vetString[0] = listaEstoque.get(i).getDescricao() + "";
                vetString[1] = listaEstoque.get(i).getId() + "";
                vetString[2] = listaEstoque.get(i).getCodigo() + "";
                vetString[3] = listaEstoque.get(i).getQuantidadePecas() + "";
                vetString[4] = listaEstoque.get(i).getValorUnidade() + "";

                if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Código")) {
                    if (String.valueOf(listaEstoque.get(i).getCodigo()).contains(jTextField1campoBusca.getText())) {
                        model.addRow(vetString);
                        contem = true;

                    }

                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("ID")) {
                    if (String.valueOf(listaEstoque.get(i).getId()).contains(jTextField1campoBusca.getText())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Descrição")) {
                    if (listaEstoque.get(i).getDescricao().toUpperCase().contains(jTextField1campoBusca.getText().toUpperCase())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                }
            }
            if (contem == false) {
                throw new Exception("Peça não encontrada!");

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipalEstoque.consultae = false;
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextField1campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1campoBuscaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        TelaPrincipalEstoque.consultae = true;
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        try {
            EstoqueDao excluir = new EstoqueDao();
            EstoqueDao lista = new EstoqueDao();
            ArrayList<estoque> listaEstoque = null;
            listaEstoque = lista.obterPecas();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            String[] vetString = new String[9];
            String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 1);

            for (int i = 0; i < listaEstoque.size(); i++) {

                if (String.valueOf(listaEstoque.get(i).getId()).equals(usuario)) {

                    excluir.excluir(listaEstoque.get(i).getId());

                }

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }


    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void JtableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMouseClicked
        try {
            if (attestoque == false) {
                TelaAtualizarEstoque atualizare = new TelaAtualizarEstoque();
                jConsultae.add(atualizare);
                atualizare.setVisible(true);
                atualizare.setPosicao();
                DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
                String[] vetString = new String[9];
                String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 1);
                EstoqueDao metodos = new EstoqueDao();
                ArrayList<estoque> listaEstoque = null;
                listaEstoque = metodos.obterPecas();
                atualizare.txtIDpeca.setText(usuario);
                for (int i = 0; i < listaEstoque.size(); i++) {
                    if (atualizare.txtIDpeca.getText().equals(String.valueOf(listaEstoque.get(i).getId()))) {
                        atualizare.txtCodigoDePecas.setText("" + listaEstoque.get(i).getCodigo());
                        atualizare.txtDescricao.setText("" + listaEstoque.get(i).getDescricao());
                        atualizare.txtQuantidade.setText("" + listaEstoque.get(i).getQuantidadePecas());
                        atualizare.txtValorU.setText("" + listaEstoque.get(i).getValorUnidade());

                    }

                }

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }


    }//GEN-LAST:event_JtableSaidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable JtableSaida;
    private javax.swing.JToggleButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JDesktopPane jConsultae;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextField1campoBusca;
    private javax.swing.JComboBox<String> jctipodeOpcaoDeBusca;
    // End of variables declaration//GEN-END:variables

}
