/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import classes.colaborador;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistenciaColaborador.ColaboradorDao;

/**
 *
 * @author cabec
 */
public class TelaConsultaColaborador extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaColaborador
     */
    public TelaConsultaColaborador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jConsultaColaborador = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonexcluir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();
        JtableSaida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jctipodeOpcaoDeBusca = new javax.swing.JComboBox<>();
        jTextField1campoBuscaColaborador = new javax.swing.JTextField();
        jCPF = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setTitle("Consulta Colaborador");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButtonexcluir.setBackground(new java.awt.Color(255, 51, 0));
        jButtonexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-trash-16.png"))); // NOI18N
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 187, 0, 0);
        jPanel1.add(jButtonexcluir, gridBagConstraints);

        jButtonBuscar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 27, 0, 0);
        jPanel1.add(jButtonBuscar, gridBagConstraints);

        JtableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "ID", "Endereço", "Email", "CPF", "Data Nascimento", "Especialidade", "Salário Hora", "Salário Mensal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableSaidaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JtableSaidaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JtableSaidaMouseReleased(evt);
            }
        });
        jScrollPane.setViewportView(JtableSaida);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 839;
        gridBagConstraints.ipady = 355;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 17, 0, 18);
        jPanel1.add(jScrollPane, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jctipodeOpcaoDeBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nome", "CPF", "Especialidade" }));
        jctipodeOpcaoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipodeOpcaoDeBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -4;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 0, 0);
        jPanel1.add(jctipodeOpcaoDeBusca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jTextField1campoBuscaColaborador, gridBagConstraints);

        try {
            jCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jCPF, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 33, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jButtonVoltar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 0, 0);
        jPanel1.add(jButtonVoltar, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Voltar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 2, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jConsultaColaborador.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jConsultaColaboradorLayout = new javax.swing.GroupLayout(jConsultaColaborador);
        jConsultaColaborador.setLayout(jConsultaColaboradorLayout);
        jConsultaColaboradorLayout.setHorizontalGroup(
            jConsultaColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jConsultaColaboradorLayout.setVerticalGroup(
            jConsultaColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jConsultaColaborador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jConsultaColaborador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        try {
            ColaboradorDao excluir = new ColaboradorDao();
            ColaboradorDao lista = new ColaboradorDao();
            ArrayList<colaborador> listaColaborador = null;
            listaColaborador = lista.obterColaborador();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            String[] vetString = new String[9];
            String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 2);

            for (int i = 0; i < listaColaborador.size(); i++) {

                if (String.valueOf(listaColaborador.get(i).getID()).equals(usuario)) {

                    excluir.excluir(listaColaborador.get(i).getID());

                }

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }


    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            ColaboradorDao metodos = new ColaboradorDao();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            ArrayList<colaborador> listaColaborador = null;
            listaColaborador = metodos.obterColaborador();
            String[] vetString = new String[10];
            String saida = "";
            model.setRowCount(0);
            boolean contem = false;

            for (int i = 0; i < listaColaborador.size(); i++) {

                vetString[0] = listaColaborador.get(i).getNome() + "";
                vetString[1] = listaColaborador.get(i).getTelefone() + "";
                vetString[2] = listaColaborador.get(i).getID() + "";
                vetString[3] = listaColaborador.get(i).getEndereco() + "";
                vetString[4] = listaColaborador.get(i).getEmail() + "";
                vetString[5] = listaColaborador.get(i).getCPF() + "";
                vetString[6] = new SimpleDateFormat("dd/MM/yyyy").format(listaColaborador.get(i).getDataNascimento()) + "";
                vetString[7] = listaColaborador.get(i).getEspecialidade() + "";
                vetString[8] = listaColaborador.get(i).getSalarioHora() + "";
                vetString[9] = listaColaborador.get(i).getSalarioMensal() + "";

                if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Codigo")) {
                    if (String.valueOf(listaColaborador.get(i).getID()).contains(jTextField1campoBuscaColaborador.getText())) {
                        model.addRow(vetString);
                        contem = true;

                    }

                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("CPF")) {
                    if (listaColaborador.get(i).getCPF().contains(jTextField1campoBuscaColaborador.getText())) {
                        model.addRow(vetString);
                        contem = true;

                    }
                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Nome")) {
                    if (listaColaborador.get(i).getNome().toUpperCase().contains(jTextField1campoBuscaColaborador.getText().toUpperCase())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Especialidade")) {
                    if (listaColaborador.get(i).getEspecialidade().toUpperCase().contains(jTextField1campoBuscaColaborador.getText().toUpperCase())) {
                        model.addRow(vetString);
                        contem = true;
                    }
                }
                if (contem == false) {
                    throw new Exception("Colaborador não encontrado");

                }
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }


    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jctipodeOpcaoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipodeOpcaoDeBuscaActionPerformed
        if (jctipodeOpcaoDeBusca.getSelectedItem().equals("CPF")) {
            jCPF.setVisible(true);
            jCPF.setEnabled(true);
            jTextField1campoBuscaColaborador.setVisible(false);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Especialidade")) {
            jCPF.setVisible(false);
            jCPF.setEnabled(false);
            jTextField1campoBuscaColaborador.setVisible(true);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Nome")) {
            jCPF.setVisible(false);
            jCPF.setEnabled(false);
            jTextField1campoBuscaColaborador.setVisible(true);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Codigo")) {
            jCPF.setVisible(false);
            jCPF.setEnabled(false);
            jTextField1campoBuscaColaborador.setVisible(true);
        }

    }//GEN-LAST:event_jctipodeOpcaoDeBuscaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.consultac = false;
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void JtableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMouseClicked
        try {
            TelaAtualizarColaborador atualizarc = new TelaAtualizarColaborador();
            jConsultaColaborador.add(atualizarc);
            atualizarc.setVisible(true);
            atualizarc.setPosicao();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            String[] vetString = new String[9];
            String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 2);
            ColaboradorDao metodos = new ColaboradorDao();
            ArrayList<colaborador> listaColaborador = null;
            listaColaborador = metodos.obterColaborador();
            atualizarc.txtCodigo.setText(usuario);
            for (int i = 0; i < listaColaborador.size(); i++) {
                if (atualizarc.txtCodigo.getText().equals(String.valueOf(listaColaborador.get(i).getID()))) {
                    atualizarc.txtNomeDoCliente.setText("" + listaColaborador.get(i).getNome());

                    atualizarc.jCTelefone.setSelectedItem(String.valueOf(listaColaborador.get(i).getTelefone().getTipo()));
                    atualizarc.txtCELULAR.setText("" + listaColaborador.get(i).getTelefone().getTelefone());
                    atualizarc.txtRESIDENCIAL.setText("" + listaColaborador.get(i).getTelefone().getTelefone());
                    atualizarc.txtTRABALHO.setText("" + listaColaborador.get(i).getTelefone().getTelefone());
                    atualizarc.txtCPF.setEditable(false);
                    atualizarc.txtCPF.setText("" + listaColaborador.get(i).getCPF());
                    atualizarc.txtCEP.setText("" + listaColaborador.get(i).getEndereco().getCep());
                    atualizarc.txtCidade.setText("" + listaColaborador.get(i).getEndereco().getCidade());
                    atualizarc.txtComplemento.setText("" + listaColaborador.get(i).getEndereco().getComplemento());
                    atualizarc.txtDataNascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(listaColaborador.get(i).getDataNascimento()));
                    atualizarc.txtEmail.setText("" + listaColaborador.get(i).getEmail());
                    atualizarc.txtEstado.setText("" + listaColaborador.get(i).getEndereco().getEstado());
                    atualizarc.txtLogradouro.setText("" + listaColaborador.get(i).getEndereco().getLogradouro());
                    atualizarc.txtNumero.setText("" + listaColaborador.get(i).getEndereco().getNumero());
                    atualizarc.txtBairro.setText("" + listaColaborador.get(i).getEndereco().getBairro());
                    atualizarc.jCLogradouro.setSelectedItem(String.valueOf(listaColaborador.get(i).getEndereco().getTipo()));
                    atualizarc.txtEspecialidade.setText("" + listaColaborador.get(i).getEspecialidade());
                    atualizarc.txtHora.setText("" + listaColaborador.get(i).getSalarioHora());
                    atualizarc.txtMensal.setText("" + listaColaborador.get(i).getSalarioMensal());

                }

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }


    }//GEN-LAST:event_JtableSaidaMouseClicked

    private void JtableSaidaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_JtableSaidaMouseReleased

    private void JtableSaidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMousePressed
        
    }//GEN-LAST:event_JtableSaidaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableSaida;
    private javax.swing.JToggleButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JFormattedTextField jCPF;
    private javax.swing.JDesktopPane jConsultaColaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextField1campoBuscaColaborador;
    private javax.swing.JComboBox<String> jctipodeOpcaoDeBusca;
    // End of variables declaration//GEN-END:variables

}
