/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import java.awt.Cursor;
import java.beans.PropertyVetoException;

/**
 *
 * @author cabec
 */
public class TelaPrincipalColaborador extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalColaborador
     */
    public TelaPrincipalColaborador() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    JBvoltar.setBounds(0, 0, 100, 30);
    JBvoltar.setOpaque(false);
    JBvoltar.setContentAreaFilled(false);
    JBvoltar.setBorderPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTelaPrincipalColaborador = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jAddColaborador = new javax.swing.JButton();
        jConsultarColaborador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JBvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Colaborador");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jAddColaborador.setBackground(new java.awt.Color(102, 102, 102));
        jAddColaborador.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jAddColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-group-woman-man-16.png"))); // NOI18N
        jAddColaborador.setText("Adicionar Colaborador");
        jAddColaborador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAddColaboradorMouseMoved(evt);
            }
        });
        jAddColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddColaboradorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 258, 0, 0);
        jPanel1.add(jAddColaborador, gridBagConstraints);

        jConsultarColaborador.setBackground(new java.awt.Color(102, 102, 102));
        jConsultarColaborador.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jConsultarColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-client-16.png"))); // NOI18N
        jConsultarColaborador.setText("Consultar Colaborador");
        jConsultarColaborador.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jConsultarColaboradorMouseMoved(evt);
            }
        });
        jConsultarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarColaboradorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(65, 258, 0, 0);
        jPanel1.add(jConsultarColaborador, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-collaborator-male-64.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 7, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-collaborator-male-64.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 32, 7, 6);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel3.setText("Colaborador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 45, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(96, 95, 0, 84);
        jPanel1.add(jPanel2, gridBagConstraints);

        JBvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-64 (1).png"))); // NOI18N
        JBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 77, 6, 84);
        jPanel1.add(JBvoltar, gridBagConstraints);

        jTelaPrincipalColaborador.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jTelaPrincipalColaboradorLayout = new javax.swing.GroupLayout(jTelaPrincipalColaborador);
        jTelaPrincipalColaborador.setLayout(jTelaPrincipalColaboradorLayout);
        jTelaPrincipalColaboradorLayout.setHorizontalGroup(
            jTelaPrincipalColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaPrincipalColaboradorLayout.setVerticalGroup(
            jTelaPrincipalColaboradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaPrincipalColaborador)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaPrincipalColaborador)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddColaboradorActionPerformed
        TelaCadastroColaborador cadc = new TelaCadastroColaborador();
        jTelaPrincipalColaborador.add(cadc);
        cadc.setVisible(true);
        cadc.setPosicao();
    }//GEN-LAST:event_jAddColaboradorActionPerformed

    private void jConsultarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarColaboradorActionPerformed
        TelaConsultaColaborador consultac = new TelaConsultaColaborador();
        jTelaPrincipalColaborador.add(consultac);
        consultac.show();
        try {          
        consultac.setMaximum(true);
        } catch (PropertyVetoException ex) {
      }            
    }//GEN-LAST:event_jConsultarColaboradorActionPerformed

    private void jAddColaboradorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddColaboradorMouseMoved
        jAddColaborador.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jAddColaboradorMouseMoved

    private void jConsultarColaboradorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConsultarColaboradorMouseMoved
        jConsultarColaborador.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jConsultarColaboradorMouseMoved

    private void JBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvoltarActionPerformed
        dispose();
    }//GEN-LAST:event_JBvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColaborador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalColaborador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBvoltar;
    private javax.swing.JButton jAddColaborador;
    private javax.swing.JButton jConsultarColaborador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JDesktopPane jTelaPrincipalColaborador;
    // End of variables declaration//GEN-END:variables
}
