/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import classes.cliente;
import classes.marca;
import classes.modelo;
import classes.veiculo;
import enumeradores.tipoModeloVeiculo;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistenciaCliente.ClienteDao;
import persistenciaVeiculo.veiculoDao;

/**
 *
 * @author cabec
 */
public class TelaCadastroVeiculo extends javax.swing.JInternalFrame {
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Creates new form TelaCadastroVeiculo
     */
    public TelaCadastroVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtIDCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtRenavam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jBVoltar = new javax.swing.JButton();
        jBNovo = new javax.swing.JButton();
        jBSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_saidaV = new javax.swing.JTable();
        jCTipo = new javax.swing.JComboBox<>();
        txtPlaca = new javax.swing.JFormattedTextField();
        txtAnoModelo = new javax.swing.JFormattedTextField();
        txtAnoFab = new javax.swing.JFormattedTextField();
        jEscolhaV = new javax.swing.JComboBox<>();
        jtxtBuscar = new javax.swing.JTextField();
        jButtonBuscarC = new javax.swing.JToggleButton();
        jCNPJV = new javax.swing.JFormattedTextField();
        jCPFV = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro De Veículo\n");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Do Veículo\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID Cliente");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 22, -1, -1));

        txtID.setEnabled(false);
        jPanel6.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 44, 80, -1));

        txtIDCliente.setEnabled(false);
        jPanel6.add(txtIDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 44, 80, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Marca Do Veículo");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 90, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Modelo Do Veículo");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 90, 90, -1));

        txtMarca.setEnabled(false);
        jPanel6.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 112, 101, -1));

        txtModelo.setEnabled(false);
        jPanel6.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 112, 90, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Placa");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 230, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Renavam");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 226, -1, -1));

        txtRenavam.setEnabled(false);
        jPanel6.add(txtRenavam, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 248, 90, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ano Do Modelo");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 158, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ano De Fabricação");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 158, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tipo Veículo");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 301, -1, -1));

        jBVoltar.setBackground(new java.awt.Color(255, 51, 0));
        jBVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });
        jPanel6.add(jBVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 373, 50, 45));

        jBNovo.setBackground(new java.awt.Color(0, 0, 255));
        jBNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-macos-maximize-16.png"))); // NOI18N
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });
        jPanel6.add(jBNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 373, 50, 45));

        jBSalvar.setBackground(new java.awt.Color(51, 255, 0));
        jBSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-save-16 (1).png"))); // NOI18N
        jBSalvar.setEnabled(false);
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });
        jPanel6.add(jBSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 373, 50, 45));

        jTable_saidaV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "ID", "Endereço", "Email", "Tipo De Cliente", "CPF_CNPJ", "Data Nascimento", "Razão Social"
            }
        ));
        jTable_saidaV.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable_saidaVAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTable_saidaVAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTable_saidaVAncestorRemoved(evt);
            }
        });
        jTable_saidaV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_saidaVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_saidaV);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 52, 871, 411));

        jCTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "SUV", "ESPORTIVO", "SEDAN", "RET" }));
        jCTipo.setEnabled(false);
        jPanel6.add(jCTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 327, 101, -1));

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPlaca.setEnabled(false);
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel6.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 252, 101, -1));

        try {
            txtAnoModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnoModelo.setEnabled(false);
        jPanel6.add(txtAnoModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 180, 101, -1));

        try {
            txtAnoFab.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnoFab.setEnabled(false);
        jPanel6.add(txtAnoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 93, -1));

        jEscolhaV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "ID", "CPF", "CNPJ" }));
        jEscolhaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolhaVActionPerformed(evt);
            }
        });
        jPanel6.add(jEscolhaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));
        jPanel6.add(jtxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 160, -1));

        jButtonBuscarC.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscarC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonBuscarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 22, 30, 20));

        try {
            jCNPJV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(jCNPJV, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 160, -1));

        try {
            jCPFV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel6.add(jCPFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 160, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        TelaPrincipal.cveiculo = true;
    }//GEN-LAST:event_formInternalFrameOpened

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.cveiculo = false;
        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        novo();  
    }//GEN-LAST:event_jBNovoActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        salvar();
        try {
            veiculoDao metodos = new veiculoDao();
            veiculo cadastarVeiculo = new veiculo();
            marca cadastrarMarca = new marca();
            modelo cadastrarModelo = new modelo();
            
            cadastrarMarca.setDescricao(txtMarca.getText());
            cadastrarMarca.setLogo("...");
            
            cadastrarModelo.setAnoFabricacao(Integer.valueOf(txtAnoFab.getText()));
            cadastrarModelo.setAnoModelo(Integer.valueOf(txtAnoModelo.getText()));
            cadastrarModelo.setDescricao(txtModelo.getText());
            
            cadastarVeiculo.setID(WIDTH);
            cadastarVeiculo.setIdCliente(Integer.valueOf(txtIDCliente.getText()));
            cadastarVeiculo.setMarcaVeiculo(cadastrarMarca);
            cadastarVeiculo.setModeloVeiculo(cadastrarModelo);
            if (!cadastarVeiculo.setPlaca(txtPlaca.getText())) {
                    throw new Exception("Placa Inválida!");
            }
            cadastarVeiculo.setRenavam(txtRenavam.getText());
            if (jCTipo.getSelectedItem().equals("SUV")) {
                cadastarVeiculo.setTipo(tipoModeloVeiculo.SUV);
            } else if (jCTipo.getSelectedItem().equals("ESPORTIVO")) {
                cadastarVeiculo.setTipo(tipoModeloVeiculo.ESPORTIVO);
            } else if (jCTipo.getSelectedObjects().equals("SEDAN")) {
                cadastarVeiculo.setTipo(tipoModeloVeiculo.SEDAN);
            } else {
                cadastarVeiculo.setTipo(tipoModeloVeiculo.RET);
            }
            metodos.incluir(cadastarVeiculo);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        

    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jTable_saidaVAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable_saidaVAncestorAdded
        jTable_saidaV.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable_saidaV.getColumnModel().getColumn(2).setPreferredWidth(25);
        

    }//GEN-LAST:event_jTable_saidaVAncestorAdded

    private void jTable_saidaVAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable_saidaVAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_saidaVAncestorMoved

    private void jTable_saidaVAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable_saidaVAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_saidaVAncestorRemoved

    private void jTable_saidaVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_saidaVMouseClicked
        try {
            
            ClienteDao lista = new ClienteDao();
            ArrayList<cliente> lista_cliente = null;
            lista_cliente = lista.obterClientes();
            String usuario = "" + jTable_saidaV.getValueAt(jTable_saidaV.getSelectedRow(), 2);
            
            for (int i = 0; i < lista_cliente.size(); i++) {
                
                if (String.valueOf(lista_cliente.get(i).getID()).equals(usuario)) {

                    //txtIDCliente.setText("" + lista_cliente.get(i).getID());
                    txtIDCliente.setText("" + lista_cliente.get(i).getID());
                }
                
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        

    }//GEN-LAST:event_jTable_saidaVMouseClicked

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed

    }//GEN-LAST:event_txtPlacaActionPerformed

    private void jButtonBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCActionPerformed
        try {
            ClienteDao lista = new ClienteDao();
            DefaultTableModel model = (DefaultTableModel) jTable_saidaV.getModel();

            ArrayList<cliente> listaCliente = null;
            listaCliente = lista.obterClientes();
            String[] vetString = new String[9];
            String saida = "";
            model.setRowCount(0);
            boolean contem = false;
            for (int i = 0; i < listaCliente.size(); i++) {

                vetString[0] = listaCliente.get(i).getNome() + "";
                vetString[1] = listaCliente.get(i).getTelefone() + "";
                vetString[2] = listaCliente.get(i).getID() + "";
                vetString[3] = listaCliente.get(i).getEndereco() + "";
                vetString[4] = listaCliente.get(i).getEmail() + "";
                vetString[5] = listaCliente.get(i).getTipoCliente() + "";
                vetString[6] = listaCliente.get(i).getCPF_CNPJ() + "";
                vetString[7] = listaCliente.get(i).getDataNascimento() + "";
                vetString[8] = listaCliente.get(i).getRazaoSocial() + "";

                if (jEscolhaV.getSelectedItem().equals("ID")) {
                    if (String.valueOf(listaCliente.get(i).getID()).contains(jtxtBuscar.getText())) {
                        model.addRow(vetString);
                        contem = true;

                    }

                } else if (jEscolhaV.getSelectedItem().equals("Nome")) {
                    if (listaCliente.get(i).getNome().toUpperCase().contains(jtxtBuscar.getText().toUpperCase())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                    //
                } else if (jEscolhaV.getSelectedItem().equals("CPF")) {
                    if (listaCliente.get(i).getCPF_CNPJ().contains(jCPFV.getText())) {
                        model.addRow(vetString);
                        contem = true;
                    }
                } else if (jEscolhaV.getSelectedItem().equals("CNPJ")) {
                    if (listaCliente.get(i).getCPF_CNPJ().contains(jCNPJV.getText())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                    //
                }
            }
            if (contem == false) {
                throw new Exception("Cliente não encontrado");

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscarCActionPerformed

    private void jEscolhaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolhaVActionPerformed
            if (jEscolhaV.getSelectedItem().equals("CPF")) {
            jCPFV.setVisible(true);
            jCPFV.setEnabled(true);
            jCNPJV.setVisible(false);
            jCNPJV.setEnabled(false);
            jtxtBuscar.setVisible(false);
            jtxtBuscar.setEnabled(false); 
        } else if (jEscolhaV.getSelectedItem().equals("CNPJ")) {
            jCNPJV.setVisible(true);
            jCNPJV.setEnabled(true);
            jCPFV.setVisible(false);
            jCPFV.setEnabled(false);
            jtxtBuscar.setVisible(false);
            jtxtBuscar.setEnabled(false); 
        } else if (jEscolhaV.getSelectedItem().equals("Nome")) {
            jCNPJV.setVisible(false);
            jCNPJV.setEnabled(false);
            jCPFV.setVisible(false);
            jCPFV.setEnabled(false);
            jtxtBuscar.setVisible(true);
            jtxtBuscar.setEnabled(true); 
        } else if (jEscolhaV.getSelectedItem().equals("ID")) {
            jCNPJV.setVisible(false);
            jCNPJV.setEnabled(false);
            jCPFV.setVisible(false);
            jCPFV.setEnabled(false);
            jtxtBuscar.setVisible(true);
            jtxtBuscar.setEnabled(true);          
        }
    }//GEN-LAST:event_jEscolhaVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBNovo;
    public javax.swing.JButton jBSalvar;
    public javax.swing.JButton jBVoltar;
    public javax.swing.JToggleButton jButtonBuscarC;
    public javax.swing.JFormattedTextField jCNPJV;
    public javax.swing.JFormattedTextField jCPFV;
    public javax.swing.JComboBox<String> jCTipo;
    public javax.swing.JComboBox<String> jEscolhaV;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_saidaV;
    public javax.swing.JTextField jtxtBuscar;
    public javax.swing.JFormattedTextField txtAnoFab;
    public javax.swing.JFormattedTextField txtAnoModelo;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtIDCliente;
    public javax.swing.JTextField txtMarca;
    public javax.swing.JTextField txtModelo;
    public javax.swing.JFormattedTextField txtPlaca;
    public javax.swing.JTextField txtRenavam;
    // End of variables declaration//GEN-END:variables

    public void novo() {
        txtID.setEnabled(true);
        txtID.setEditable(false);
        txtIDCliente.setEnabled(true);
        txtAnoModelo.setEnabled(true);
        txtModelo.setEnabled(true);
        txtMarca.setEnabled(true);
        txtAnoFab.setEnabled(true);
        txtPlaca.setEnabled(true);
        jCTipo.setEnabled(true);
        txtRenavam.setEnabled(true);
        txtPlaca.setEnabled(true);
        txtIDCliente.setEditable(false);
        txtAnoModelo.setText("");
        txtModelo.setText("");
        txtMarca.setText("");
        txtAnoFab.setText("");
        txtPlaca.setText("");
        txtRenavam.setText("");
        jBSalvar.setEnabled(true);
    }
    
    public void editar() {
        txtID.setEnabled(false);
        txtIDCliente.setEnabled(true);
        txtAnoModelo.setEnabled(true);
        txtModelo.setEnabled(true);
        txtMarca.setEnabled(true);
        txtAnoFab.setEnabled(true);
        txtPlaca.setEnabled(true);
        jCTipo.setEnabled(true);
        txtRenavam.setEnabled(true);
        jBSalvar.setEnabled(true);
    }
    
    public void salvar() {
        txtID.setEnabled(false);
        txtIDCliente.setEnabled(false);
        txtAnoModelo.setEnabled(false);
        txtModelo.setEnabled(false);
        txtMarca.setEnabled(false);
        txtAnoFab.setEnabled(false);
        txtPlaca.setEnabled(false);
        jCTipo.setEnabled(false);
        txtRenavam.setEnabled(false);
        jBSalvar.setEnabled(false);
        
    }
}
