/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

/**
 *
 * @author cabec
 */
public class TelaConsultaServico extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConsultaServico
     */
    public TelaConsultaServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTelaConsultaServico = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVoltar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonexcluir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();
        JtableSaida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jctipodeOpcaoDeBusca = new javax.swing.JComboBox<>();
        jTextcampoBuscaServico = new javax.swing.JTextField();

        setTitle("Consulta Serviço");

        jTelaConsultaServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTelaConsultaServicoMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 33, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jButtonVoltar1.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButtonVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 23, 0, 0);
        jPanel1.add(jButtonVoltar1, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Voltar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 41, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jButtonexcluir.setBackground(new java.awt.Color(255, 51, 0));
        jButtonexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-trash-16.png"))); // NOI18N
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 187, 0, 0);
        jPanel1.add(jButtonexcluir, gridBagConstraints);

        jButtonBuscar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 27, 0, 0);
        jPanel1.add(jButtonBuscar, gridBagConstraints);

        JtableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo Serviço", "Descrição", "Valor", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableSaidaMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(JtableSaida);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 854;
        gridBagConstraints.ipady = 762;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 23, 0, 23);
        jPanel1.add(jScrollPane, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 26, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jctipodeOpcaoDeBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Serviço", "Tipo De Serviço", " " }));
        jctipodeOpcaoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipodeOpcaoDeBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -14;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(48, 6, 0, 0);
        jPanel1.add(jctipodeOpcaoDeBusca, gridBagConstraints);

        jTextcampoBuscaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcampoBuscaServicoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 18, 0, 0);
        jPanel1.add(jTextcampoBuscaServico, gridBagConstraints);

        jTelaConsultaServico.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jTelaConsultaServicoLayout = new javax.swing.GroupLayout(jTelaConsultaServico);
        jTelaConsultaServico.setLayout(jTelaConsultaServicoLayout);
        jTelaConsultaServicoLayout.setHorizontalGroup(
            jTelaConsultaServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaConsultaServicoLayout.setVerticalGroup(
            jTelaConsultaServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaConsultaServico)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaConsultaServico)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltar1ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.consultac = false;
        dispose();
    }//GEN-LAST:event_jButtonVoltar1ActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed

    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void JtableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMouseClicked

    }//GEN-LAST:event_JtableSaidaMouseClicked

    private void jctipodeOpcaoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipodeOpcaoDeBuscaActionPerformed
        if (jctipodeOpcaoDeBusca.getSelectedItem().equals("ID")) {
            jTextcampoBuscaServico.setVisible(true);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Serviço")) {
            jTextcampoBuscaServico.setVisible(true);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Tipo Serviço")) {
            jTextcampoBuscaServico.setVisible(true);
        }
    }//GEN-LAST:event_jctipodeOpcaoDeBuscaActionPerformed

    private void jTextcampoBuscaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcampoBuscaServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcampoBuscaServicoActionPerformed

    private void jTelaConsultaServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTelaConsultaServicoMouseClicked
        TelaAtualizarServico atts = new TelaAtualizarServico();
        jTelaConsultaServico.add(atts);
        atts.setVisible(true);
        atts.setPosicao();
    }//GEN-LAST:event_jTelaConsultaServicoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableSaida;
    private javax.swing.JToggleButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar1;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JDesktopPane jTelaConsultaServico;
    private javax.swing.JTextField jTextcampoBuscaServico;
    private javax.swing.JComboBox<String> jctipodeOpcaoDeBusca;
    // End of variables declaration//GEN-END:variables
}
