/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Tela.TelaAddEstoque;
import Tela.TelaConsultaEstoque;
import java.awt.Cursor;
import java.beans.PropertyVetoException;

/**
 *
 * @author ALUNO
 */
public class TelaPrincipalEstoque extends javax.swing.JFrame {
    
    public static boolean adicionar;
    public static boolean consultae;

    /**
     * Creates new form TelaPrincipalEstoque
     */
    public TelaPrincipalEstoque() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    JBvoltar.setBounds(0, 0, 100, 30);
    JBvoltar.setOpaque(false);
    JBvoltar.setContentAreaFilled(false);
    JBvoltar.setBorderPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTelaEstoque = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jAddEstoque = new javax.swing.JButton();
        jConsultaE = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JBvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque\n");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jAddEstoque.setBackground(new java.awt.Color(102, 102, 102));
        jAddEstoque.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jAddEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-scan-stock-16.png"))); // NOI18N
        jAddEstoque.setText("Adicionar Estoque");
        jAddEstoque.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAddEstoqueMouseMoved(evt);
            }
        });
        jAddEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddEstoqueActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 242, 0, 0);
        jPanel2.add(jAddEstoque, gridBagConstraints);

        jConsultaE.setBackground(new java.awt.Color(102, 102, 102));
        jConsultaE.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jConsultaE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-in-list-16.png"))); // NOI18N
        jConsultaE.setText("Consultar Estoque");
        jConsultaE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jConsultaEMouseMoved(evt);
            }
        });
        jConsultaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultaEActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 242, 0, 0);
        jPanel2.add(jConsultaE, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-stock-64.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 14, 0);
        jPanel3.add(jLabel1, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-stock-64.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 62, 14, 6);
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 48)); // NOI18N
        jLabel3.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 75, 14, 0);
        jPanel3.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(56, 68, 0, 63);
        jPanel2.add(jPanel3, gridBagConstraints);

        JBvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-64 (1).png"))); // NOI18N
        JBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBvoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 82, 0, 63);
        jPanel2.add(JBvoltar, gridBagConstraints);

        jTelaEstoque.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jTelaEstoqueLayout = new javax.swing.GroupLayout(jTelaEstoque);
        jTelaEstoque.setLayout(jTelaEstoqueLayout);
        jTelaEstoqueLayout.setHorizontalGroup(
            jTelaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaEstoqueLayout.setVerticalGroup(
            jTelaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaEstoque)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaEstoque)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddEstoqueActionPerformed
        // TODO add your handling code here:
        if (adicionar==false){
        TelaAddEstoque Estq = new TelaAddEstoque();
        jTelaEstoque.add(Estq);
        Estq.setVisible(true); 
        Estq.setPosicao();
    }//GEN-LAST:event_jAddEstoqueActionPerformed
}
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TelaAddEstoque.adicionar=false;
    }//GEN-LAST:event_formWindowOpened

    private void jConsultaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultaEActionPerformed
        if (consultae==false){
        TelaConsultaEstoque consulte = new TelaConsultaEstoque();
        jTelaEstoque.add(consulte);
        consulte.show();
        try {          
        consulte.setMaximum(true);
        } catch (PropertyVetoException ex) {
       }       
    }//GEN-LAST:event_jConsultaEActionPerformed
}
    private void jAddEstoqueMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddEstoqueMouseMoved
        jAddEstoque.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jAddEstoqueMouseMoved

    private void jConsultaEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jConsultaEMouseMoved
        jConsultaE.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jConsultaEMouseMoved

    private void JBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBvoltarActionPerformed
        dispose();
    }//GEN-LAST:event_JBvoltarActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBvoltar;
    private javax.swing.JButton jAddEstoque;
    private javax.swing.JButton jConsultaE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane jTelaEstoque;
    // End of variables declaration//GEN-END:variables
}
