/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import Tela.TelaAtualizarCliente;
import static Tela.TelaPrincipal.cadastro;
import classes.cliente;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistenciaCliente.ClienteDao;

/**
 *
 * @author cabec
 */
public class TelaConsulta extends javax.swing.JInternalFrame {

    public static boolean consultac;

    /**
     * Creates new form TelaConsultaa
     */
    public TelaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTelaConsulta = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonexcluir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();
        JtableSaida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jctipodeOpcaoDeBusca = new javax.swing.JComboBox<>();
        jTextField1campoBusca = new javax.swing.JTextField();
        jCPF = new javax.swing.JFormattedTextField();
        jCNPJ = new javax.swing.JFormattedTextField();

        setTitle("Tela Consulta");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 187, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 33, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jButtonVoltar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 23, 0, 0);
        jPanel1.add(jButtonVoltar, gridBagConstraints);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Voltar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 27, 30, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jButtonexcluir.setBackground(new java.awt.Color(255, 51, 0));
        jButtonexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-trash-16.png"))); // NOI18N
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 187, 0, 0);
        jPanel1.add(jButtonexcluir, gridBagConstraints);

        jButtonBuscar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 27, 0, 0);
        jPanel1.add(jButtonBuscar, gridBagConstraints);

        JtableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "ID", "Endereço", "Email", "Tipo Pessoa", "CPF/CNPJ", "Data Nascimento", "Razão Social"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableSaidaMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(JtableSaida);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 839;
        gridBagConstraints.ipady = 355;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 0, 0);
        jPanel1.add(jScrollPane, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jctipodeOpcaoDeBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo", "Nome", "CPF", "CNPJ" }));
        jctipodeOpcaoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipodeOpcaoDeBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 0, 0);
        jPanel1.add(jctipodeOpcaoDeBusca, gridBagConstraints);

        jTextField1campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1campoBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jTextField1campoBusca, gridBagConstraints);

        try {
            jCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCPF.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jCPF, gridBagConstraints);

        try {
            jCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCNPJ.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        jPanel1.add(jCNPJ, gridBagConstraints);

        jTelaConsulta.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jTelaConsultaLayout = new javax.swing.GroupLayout(jTelaConsulta);
        jTelaConsulta.setLayout(jTelaConsultaLayout);
        jTelaConsultaLayout.setHorizontalGroup(
            jTelaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );
        jTelaConsultaLayout.setVerticalGroup(
            jTelaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaConsulta)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaConsulta)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.consultac = false;
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        try {
            ClienteDao excluir = new ClienteDao();
            ClienteDao lista = new ClienteDao();
            ArrayList<cliente> lista_cliente = null;
            lista_cliente = lista.obterClientes();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            String[] vetString = new String[9];
            String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 2);

            for (int i = 0; i < lista_cliente.size(); i++) {

                if (String.valueOf(lista_cliente.get(i).getID()).equals(usuario)) {

                    excluir.excluir(lista_cliente.get(i).getID());

                }

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButtonexcluirActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            ClienteDao lista = new ClienteDao();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();

            ArrayList<cliente> listaCliente = null;
            listaCliente = lista.obterClientes();
            String[] vetString = new String[9];
            model.setRowCount(0);
            boolean contem = false;

            for (int i = 0; i < listaCliente.size(); i++) {

                vetString[0] = listaCliente.get(i).getNome() + "";
                vetString[1] = listaCliente.get(i).getTelefone() + "";
                vetString[2] = listaCliente.get(i).getID() + "";
                vetString[3] = listaCliente.get(i).getEndereco() + "";
                vetString[4] = listaCliente.get(i).getEmail() + "";
                vetString[5] = listaCliente.get(i).getTipoCliente() + "";
                vetString[6] = listaCliente.get(i).getCPF_CNPJ() + "";
                vetString[7] = new SimpleDateFormat("dd/MM/yyyy").format(listaCliente.get(i).getDataNascimento()) + "";
                vetString[8] = listaCliente.get(i).getRazaoSocial() + "";

                if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Codigo")) {
                    if (String.valueOf(listaCliente.get(i).getID()).contains(jTextField1campoBusca.getText())) {
                        model.addRow(vetString);
                        contem = true;

                    }

                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Nome")) {
                    if (listaCliente.get(i).getNome().toUpperCase().contains(jTextField1campoBusca.getText().toUpperCase())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                    //
                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("CPF")) {
                    if (listaCliente.get(i).getCPF_CNPJ().contains(jCPF.getText())) {
                        model.addRow(vetString);
                        contem = true;
                    }
                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("CNPJ")) {
                    if (listaCliente.get(i).getCPF_CNPJ().contains(jCNPJ.getText())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                    //
                }
            }
            if (contem == false) {
                throw new Exception("Cliente não encontrado");

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jctipodeOpcaoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipodeOpcaoDeBuscaActionPerformed
        if (jctipodeOpcaoDeBusca.getSelectedItem().equals("CPF")) {
            jCPF.setVisible(true);
            jCPF.setEnabled(true);
            jCNPJ.setVisible(false);
            jCNPJ.setEnabled(false);
            jTextField1campoBusca.setVisible(false);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("CNPJ")) {
            jCNPJ.setVisible(true);
            jCNPJ.setEnabled(true);
            jCPF.setVisible(false);
            jCPF.setEnabled(false);
            jTextField1campoBusca.setVisible(false);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Nome")) {
            jCNPJ.setVisible(false);
            jCNPJ.setEnabled(false);
            jCPF.setVisible(false);
            jCPF.setEnabled(false);
            jTextField1campoBusca.setVisible(true);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Codigo")) {
            jCNPJ.setVisible(false);
            jCNPJ.setEnabled(false);
            jCPF.setVisible(false);
            jCPF.setEnabled(false);
            jTextField1campoBusca.setVisible(true);
        }
    }//GEN-LAST:event_jctipodeOpcaoDeBuscaActionPerformed

    private void jTextField1campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1campoBuscaActionPerformed

    private void JtableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMouseClicked
        try {
            TelaAtualizarCliente atualizar = new TelaAtualizarCliente();
            jTelaConsulta.add(atualizar);
            atualizar.setVisible(true);
            atualizar.setPosicao();

            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            String[] vetString = new String[9];
            String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 2);
            atualizar.txtCodigo.setText(usuario);
            ClienteDao metodos = new ClienteDao();
            ArrayList<cliente> listaClientes = null;
            listaClientes = metodos.obterClientes();

            for (int i = 0; i < listaClientes.size(); i++) {
                if (atualizar.txtCodigo.getText().equals(String.valueOf(listaClientes.get(i).getID()))) {
                    atualizar.txtNomeDoCliente.setText("" + listaClientes.get(i).getNome());
                    atualizar.jCTelefone.setSelectedItem(String.valueOf(listaClientes.get(i).getTelefone().getTipo()));
                    atualizar.txtCELULAR.setText("" + listaClientes.get(i).getTelefone().getTelefone());
                    atualizar.txtRESIDENCIAL.setText("" + listaClientes.get(i).getTelefone().getTelefone());
                    atualizar.txtTRABALHO.setText("" + listaClientes.get(i).getTelefone().getTelefone());
                    atualizar.jCSocial.setSelectedItem(String.valueOf(listaClientes.get(i).getTipoCliente()));
                    atualizar.jCSocial.setEnabled(false);
                    atualizar.txtCNPJ.setEditable(false);
                    atualizar.txtCPF.setEditable(false);
                    atualizar.txtCPF.setText("" + listaClientes.get(i).getCPF_CNPJ());
                    atualizar.txtCNPJ.setText("" + listaClientes.get(i).getCPF_CNPJ());
                    atualizar.txtCEP.setText("" + listaClientes.get(i).getEndereco().getCep());
                    atualizar.txtCidade.setText("" + listaClientes.get(i).getEndereco().getCidade());
                    atualizar.txtComplemento.setText("" + listaClientes.get(i).getEndereco().getComplemento());
                    atualizar.txtDataNascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(listaClientes.get(i).getDataNascimento()));
                    atualizar.txtEmail.setText("" + listaClientes.get(i).getEmail());
                    atualizar.txtEstado.setText("" + listaClientes.get(i).getEndereco().getEstado());
                    atualizar.txtLogradouro.setText("" + listaClientes.get(i).getEndereco().getLogradouro());
                    atualizar.txtNumero.setText("" + listaClientes.get(i).getEndereco().getNumero());
                    atualizar.txtBairro.setText("" + listaClientes.get(i).getEndereco().getBairro());
                    atualizar.jCLogradouro.setSelectedItem(String.valueOf(listaClientes.get(i).getEndereco().getTipo()));
                    atualizar.txtRazaoSocial.setText("" + listaClientes.get(i).getRazaoSocial());
                }

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }


    }//GEN-LAST:event_JtableSaidaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableSaida;
    private javax.swing.JToggleButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JFormattedTextField jCNPJ;
    private javax.swing.JFormattedTextField jCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JDesktopPane jTelaConsulta;
    private javax.swing.JTextField jTextField1campoBusca;
    private javax.swing.JComboBox<String> jctipodeOpcaoDeBusca;
    // End of variables declaration//GEN-END:variables
}
