/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import Tela.TelaCadastroColaborador;
import java.awt.Cursor;
import java.awt.FlowLayout;

/**
 *
 * @author cabec
 */
public class TelaMenu extends javax.swing.JFrame {
    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBEstoque = new javax.swing.JButton();
        jBGerais = new javax.swing.JButton();
        jBMecanico = new javax.swing.JButton();
        jBAtendente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBEstoque.setBackground(new java.awt.Color(102, 51, 0));
        jBEstoque.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jBEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-stock-16.png"))); // NOI18N
        jBEstoque.setText("Estoque");
        jBEstoque.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBEstoque.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBEstoqueMouseMoved(evt);
            }
        });
        jBEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(jBEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 176, 26));

        jBGerais.setBackground(new java.awt.Color(102, 51, 0));
        jBGerais.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jBGerais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-administration-16.png"))); // NOI18N
        jBGerais.setText("Geral");
        jBGerais.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBGeraisMouseMoved(evt);
            }
        });
        jBGerais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGeraisActionPerformed(evt);
            }
        });
        getContentPane().add(jBGerais, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 176, 26));

        jBMecanico.setBackground(new java.awt.Color(102, 51, 0));
        jBMecanico.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jBMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-mechanic-16 (1).png"))); // NOI18N
        jBMecanico.setText("Consultor Técnico");
        jBMecanico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBMecanicoMouseMoved(evt);
            }
        });
        jBMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMecanicoActionPerformed(evt);
            }
        });
        getContentPane().add(jBMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 176, 26));

        jBAtendente.setBackground(new java.awt.Color(102, 51, 0));
        jBAtendente.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jBAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-clerk-16.png"))); // NOI18N
        jBAtendente.setText("Atendente");
        jBAtendente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBAtendenteMouseMoved(evt);
            }
        });
        jBAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtendenteActionPerformed(evt);
            }
        });
        getContentPane().add(jBAtendente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 176, 26));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Selecione sua função");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 80, 320, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/Projeto-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 0, -1, 499));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/painel-login.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 85, 380, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car-spare-parts-old-car-spare-parts-wooden-flat-lay-workbench-background-copy-space-180744043.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, 533));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:      
    }//GEN-LAST:event_formWindowOpened

    private void jBEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEstoqueActionPerformed
        TelaPrincipalEstoque telape = new TelaPrincipalEstoque();
        telape.setVisible(true);
    }//GEN-LAST:event_jBEstoqueActionPerformed

    private void jBGeraisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGeraisActionPerformed
        TelaPrincipalGeral telag = new TelaPrincipalGeral();
        telag.setVisible(true);
    }//GEN-LAST:event_jBGeraisActionPerformed

    private void jBMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMecanicoActionPerformed
        TelaPrincipalConsultor telaconsultor = new TelaPrincipalConsultor();
        telaconsultor.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jBMecanicoActionPerformed

    private void jBAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtendenteActionPerformed
        // TODO add your handling code here:
        TelaPrincipal telap = new TelaPrincipal();
        telap.setVisible(true);
    }//GEN-LAST:event_jBAtendenteActionPerformed

    private void jBAtendenteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAtendenteMouseMoved
        jBAtendente.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBAtendenteMouseMoved

    private void jBMecanicoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBMecanicoMouseMoved
        jBMecanico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBMecanicoMouseMoved

    private void jBEstoqueMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEstoqueMouseMoved
        jBEstoque.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBEstoqueMouseMoved

    private void jBGeraisMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBGeraisMouseMoved
        jBGerais.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jBGeraisMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtendente;
    private javax.swing.JButton jBEstoque;
    private javax.swing.JButton jBGerais;
    private javax.swing.JButton jBMecanico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
