/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import javax.swing.JOptionPane;
import classes.*;
import enumeradores.*;
import java.awt.Dimension;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistenciaCliente.*;
import persistenciaVeiculo.*;

/**
 *
 * @author cabec
 */
public class TelaAtualizarCliente extends javax.swing.JInternalFrame {

    public static boolean cadastro;
    int acao;
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    /**
     * Creates new form TelaCadastroClientee
     */
    public TelaAtualizarCliente() {
        initComponents();
        txtCodigo.setEnabled(true);
        txtCodigo.setEditable(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeDoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLCPF = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtCELULAR = new javax.swing.JFormattedTextField();
        txtTRABALHO = new javax.swing.JFormattedTextField();
        txtRESIDENCIAL = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jCSocial = new javax.swing.JComboBox<>();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLCPNJ = new javax.swing.JLabel();
        jCTelefone = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLRazao = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        jCLogradouro = new javax.swing.JComboBox<>();
        jlabel = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JFormattedTextField();

        setIconifiable(true);
        setTitle("Atualizar Cliente ");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar Cliente\n"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Código");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome Do Cliente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        txtNomeDoCliente.setEnabled(false);
        jPanel2.add(txtNomeDoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Nascimento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CEP");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cidade");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 130, -1, -1));

        txtCidade.setEnabled(false);
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        jPanel2.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 152, 150, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        txtEstado.setEnabled(false);
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 152, 200, -1));

        jLCPF.setBackground(new java.awt.Color(255, 255, 255));
        jLCPF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLCPF.setText("CPF");
        jPanel2.add(jLCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Endereço De E-mail");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        txtEmail.setEnabled(false);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 190, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Obs. Do Cliente:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 349, -1, -1));

        jButtonSalvar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-save-16 (1).png"))); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 48, 42));

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setEnabled(false);
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        jPanel2.add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 90, -1));

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setEnabled(false);
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        jPanel2.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 107, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setEnabled(false);
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        jPanel2.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 200, -1));

        try {
            txtCELULAR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCELULAR.setEnabled(false);
        jPanel2.add(txtCELULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, -1));

        try {
            txtTRABALHO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTRABALHO.setEnabled(false);
        jPanel2.add(txtTRABALHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, -1));

        try {
            txtRESIDENCIAL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRESIDENCIAL.setEnabled(false);
        jPanel2.add(txtRESIDENCIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 48, 42));

        jButtonEditar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-edit-16 (1).png"))); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 48, 42));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bairro");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 130, -1, -1));

        txtBairro.setEnabled(false);
        jPanel2.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 152, 150, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Numero");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tipo Logradouro");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Complemento");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        txtComplemento.setEnabled(false);
        jPanel2.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 200, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Salvar");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(" Editar");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("  Voltar");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setText("Tipo De Pessoa");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jCSocial.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCSocial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "PESSOAFISICA", "PESSOAJURIDICA" }));
        jCSocial.setEnabled(false);
        jCSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSocialActionPerformed(evt);
            }
        });
        jPanel2.add(jCSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 170, -1));

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 200, -1));

        jLCPNJ.setBackground(new java.awt.Color(255, 255, 255));
        jLCPNJ.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCPNJ.setForeground(new java.awt.Color(255, 255, 255));
        jLCPNJ.setText("CNPJ");
        jPanel2.add(jLCPNJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jCTelefone.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCTelefone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "RESIDENCIAL", "CELULAR", "TRABALHO" }));
        jCTelefone.setEnabled(false);
        jCTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTelefoneActionPerformed(evt);
            }
        });
        jPanel2.add(jCTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 120, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefone");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLRazao.setBackground(new java.awt.Color(255, 255, 255));
        jLRazao.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLRazao.setForeground(new java.awt.Color(255, 255, 255));
        jLRazao.setText("Razão Social");
        jPanel2.add(jLRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        txtRazaoSocial.setEnabled(false);
        jPanel2.add(txtRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 150, -1));

        jCLogradouro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCLogradouro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "RUA", "AVENIDA" }));
        jCLogradouro.setEnabled(false);
        jCLogradouro.setPreferredSize(new java.awt.Dimension(127, 24));
        jPanel2.add(jCLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 30));

        jlabel.setBackground(new java.awt.Color(255, 255, 255));
        jlabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("Logradouro");
        jPanel2.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 200, -1, -1));

        txtLogradouro.setEnabled(false);
        jPanel2.add(txtLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 162, -1));

        try {
            txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 150, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        TelaPrincipal.cadastro = true;
        txtCPF.setVisible(false);
        jLCPF.setVisible(false);
        txtCNPJ.setVisible(false);
        jLCPNJ.setVisible(false);
        txtCELULAR.setVisible(true);
        txtTRABALHO.setVisible(false);
        txtRESIDENCIAL.setVisible(false);
        jLRazao.setVisible(false);
        txtRazaoSocial.setVisible(false);

    }//GEN-LAST:event_formInternalFrameOpened

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed

    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        acao = 2;
        editar();

        try {
            ClienteDao metodos = new ClienteDao();
            ArrayList<cliente> listaClientes = null;
            listaClientes = metodos.obterClientes();

            for (int i = 0; i < listaClientes.size(); i++) {
                if (txtCodigo.getText().equals(String.valueOf(listaClientes.get(i).getID()))) {
                    txtNomeDoCliente.setText("" + listaClientes.get(i).getNome());
                    jCTelefone.setSelectedItem(String.valueOf(listaClientes.get(i).getTelefone().getTipo()));
                    txtCELULAR.setText("" + listaClientes.get(i).getTelefone().getTelefone());
                    txtRESIDENCIAL.setText("" + listaClientes.get(i).getTelefone().getTelefone());
                    txtTRABALHO.setText("" + listaClientes.get(i).getTelefone().getTelefone());
                    jCSocial.setSelectedItem(String.valueOf(listaClientes.get(i).getTipoCliente()));
                    jCSocial.setEnabled(false);
                    txtCNPJ.setEditable(false);
                    txtCPF.setEditable(false);
                    txtCPF.setText("" + listaClientes.get(i).getCPF_CNPJ());
                    txtCNPJ.setText("" + listaClientes.get(i).getCPF_CNPJ());
                    txtCEP.setText("" + listaClientes.get(i).getEndereco().getCep());
                    txtCidade.setText("" + listaClientes.get(i).getEndereco().getCidade());
                    txtComplemento.setText("" + listaClientes.get(i).getEndereco().getComplemento());
                    txtDataNascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(listaClientes.get(i).getDataNascimento()));
                    txtEmail.setText("" + listaClientes.get(i).getEmail());
                    txtEstado.setText("" + listaClientes.get(i).getEndereco().getEstado());
                    txtLogradouro.setText("" + listaClientes.get(i).getEndereco().getLogradouro());
                    txtNumero.setText("" + listaClientes.get(i).getEndereco().getNumero());
                    txtBairro.setText("" + listaClientes.get(i).getEndereco().getBairro());
                    jCLogradouro.setSelectedItem(String.valueOf(listaClientes.get(i).getEndereco().getTipo()));
                    txtRazaoSocial.setText("" + listaClientes.get(i).getRazaoSocial());
                }

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.cadastro = false;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        salvar();
        try {

            iClienteDao metodos = new ClienteDao();
            cliente cadastrarCliente = new cliente();
            telefone cadastrarTelefone = new telefone();
            endereco cadastrarEndereco = new endereco();

            //usando objeto telefone para ler os dados escritos na tela
            if (jCTelefone.getSelectedItem().equals("RESIDENCIAL")) {
                cadastrarTelefone.setTipo(tiposTelefone.RESIDENCIAL);
                cadastrarTelefone.setTelefone(txtRESIDENCIAL.getText());

            } else if (jCTelefone.getSelectedItem().equals("TRABALHO")) {
                cadastrarTelefone.setTipo(tiposTelefone.TRABALHO);
                cadastrarTelefone.setTelefone(txtTRABALHO.getText());

            } else {
                cadastrarTelefone.setTipo(tiposTelefone.CELULAR);
                cadastrarTelefone.setTelefone(txtCELULAR.getText());
            }

            //usando objeto endereco para ler os dados escritos na tela
            cadastrarEndereco.setBairro(txtBairro.getText());
            cadastrarEndereco.setCep((txtCEP.getText()));
            cadastrarEndereco.setCidade(txtCidade.getText());
            cadastrarEndereco.setComplemento(txtComplemento.getText());
            cadastrarEndereco.setEstado(txtEstado.getText());
            cadastrarEndereco.setLogradouro(txtLogradouro.getText());
            cadastrarEndereco.setNumero(txtNumero.getText());
            cadastrarEndereco.setTipo(tipoLogradouro.RUA);

            //usando objeto cliente para ler os dados escritos na tela
            cadastrarCliente.setNome(txtNomeDoCliente.getText());
            if (jCSocial.getSelectedItem().equals("Pessoa Física")) {
                if (!cadastrarCliente.setCPF_CNPJ(txtCPF.getText())) {
                    throw new Exception("CPF Inválido!");
                }
            } else if (jCSocial.getSelectedItem().equals("Pessoa Jurídica")) {
                if (!cadastrarCliente.setCPF_CNPJ(txtCNPJ.getText())) {
                    throw new Exception("CNPJ Inválido!");
                }
            }
            cadastrarCliente.setDataNascimento(txtDataNascimento.getText());
            cadastrarCliente.setEmail(txtEmail.getText());
            cadastrarCliente.setEndereco(cadastrarEndereco);
            cadastrarCliente.setTelefone(cadastrarTelefone);
            cadastrarCliente.setID(Integer.parseInt(txtCodigo.getText()));
            if (jCSocial.getSelectedItem().equals("Pessoa Física")) {
                cadastrarCliente.setTipoCliente(tipoCliente.PESSOAFISICA);
                cadastrarCliente.setCPF_CNPJ(txtCPF.getText());
            } else {
                cadastrarCliente.setTipoCliente(tipoCliente.PESSOAJURIDICA);
                cadastrarCliente.setCPF_CNPJ(txtCNPJ.getText());
                cadastrarCliente.setRazaoSocial(txtRazaoSocial.getText());
            }

            metodos.alterar(cadastrarCliente, Integer.parseInt(txtCodigo.getText()));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void jCSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSocialActionPerformed
        if (jCSocial.getSelectedItem().equals("PESSOAFISICA")) {

            txtCPF.setEnabled(true);
            txtCPF.setVisible(true);
            jLCPF.setVisible(true);
            txtCNPJ.setVisible(false);
            jLCPNJ.setVisible(false);
            jLRazao.setVisible(false);
            txtRazaoSocial.setVisible(false);

        } else if (jCSocial.getSelectedItem().equals("PESSOAJURIDICA")) {

            txtCPF.setVisible(false);
            jLCPF.setVisible(false);
            txtCNPJ.setVisible(true);
            jLCPNJ.setVisible(true);
            jLRazao.setVisible(true);
            txtRazaoSocial.setVisible(true);
        } else if (jCSocial.getSelectedItem().equals("Selecione...")) {

            txtCPF.setVisible(false);
            jLCPF.setVisible(false);
            txtCNPJ.setVisible(false);
            jLCPNJ.setVisible(false);
            jLRazao.setVisible(false);
            txtRazaoSocial.setVisible(false);
        }

    }//GEN-LAST:event_jCSocialActionPerformed

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCPFActionPerformed

    private void jCTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTelefoneActionPerformed
        // TODO add your handling code here:
        if (jCTelefone.getSelectedItem().equals("RESIDENCIAL")) {
            txtCELULAR.setVisible(false);
            txtTRABALHO.setVisible(false);
            txtRESIDENCIAL.setVisible(true);

        } else if (jCTelefone.getSelectedItem().equals("TRABALHO")) {
            txtCELULAR.setVisible(false);
            txtTRABALHO.setVisible(true);
            txtRESIDENCIAL.setVisible(false);

        } else if (jCTelefone.getSelectedItem().equals("CELULAR")) {
            txtCELULAR.setVisible(true);
            txtTRABALHO.setVisible(false);
            txtRESIDENCIAL.setVisible(false);

        }
    }//GEN-LAST:event_jCTelefoneActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonEditar;
    public javax.swing.JButton jButtonSalvar;
    public javax.swing.JComboBox<String> jCLogradouro;
    public javax.swing.JComboBox<String> jCSocial;
    public javax.swing.JComboBox<String> jCTelefone;
    public javax.swing.JLabel jLCPF;
    public javax.swing.JLabel jLCPNJ;
    public javax.swing.JLabel jLRazao;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel jlabel;
    public javax.swing.JTextField txtBairro;
    public javax.swing.JFormattedTextField txtCELULAR;
    public javax.swing.JFormattedTextField txtCEP;
    public javax.swing.JFormattedTextField txtCNPJ;
    public javax.swing.JFormattedTextField txtCPF;
    public javax.swing.JTextField txtCidade;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtComplemento;
    public javax.swing.JFormattedTextField txtDataNascimento;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtLogradouro;
    public javax.swing.JTextField txtNomeDoCliente;
    public javax.swing.JFormattedTextField txtNumero;
    public javax.swing.JFormattedTextField txtRESIDENCIAL;
    public javax.swing.JTextField txtRazaoSocial;
    public javax.swing.JFormattedTextField txtTRABALHO;
    // End of variables declaration//GEN-END:variables

    public void novo() {
        txtNomeDoCliente.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtCEP.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEstado.setEnabled(true);
        txtCPF.setEnabled(true);
        txtLogradouro.setEnabled(true);
        txtCNPJ.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCELULAR.setEnabled(true);
        txtRESIDENCIAL.setEnabled(true);
        txtTRABALHO.setEnabled(true);
        txtEmail.setEnabled(true);
        txtNumero.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtNumero.setEnabled(true);
        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(true);
       
        txtRazaoSocial.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jCLogradouro.setEnabled(true);
        jCSocial.setEnabled(true);
        jCTelefone.setEnabled(true);
        txtNomeDoCliente.setText("");
        txtDataNascimento.setText("");
        txtCEP.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtCPF.setText("");
        txtBairro.setText("");
        txtCELULAR.setText("");
        txtRESIDENCIAL.setText("");
        txtTRABALHO.setText("");
        txtEmail.setText("");
        txtNumero.setText("");
        txtComplemento.setText("");
        txtNumero.setText("");
     
        txtRazaoSocial.setText("");
        txtCNPJ.setText("");
    }

    public void editar() {
        txtNomeDoCliente.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtCEP.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEstado.setEnabled(true);
        txtCPF.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCELULAR.setEnabled(true);
        txtRESIDENCIAL.setEnabled(true);
        txtTRABALHO.setEnabled(true);
        txtEmail.setEnabled(true);
        txtNumero.setEnabled(true);
        txtLogradouro.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtNumero.setEnabled(true);
        txtCodigo.setEnabled(false);
        txtCNPJ.setEnabled(true);
     
        txtRazaoSocial.setEnabled(true);
        jCLogradouro.setEnabled(true);
        jCSocial.setEnabled(true);
        jCTelefone.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(true);

    }

    public void salvar() {
        txtNomeDoCliente.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEstado.setEnabled(false);
        txtCPF.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCELULAR.setEnabled(false);
        txtRESIDENCIAL.setEnabled(false);
        txtTRABALHO.setEnabled(false);
        txtEmail.setEnabled(false);
        txtNumero.setEnabled(false);
        txtLogradouro.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtNumero.setEnabled(false);
        txtCodigo.setEnabled(false);
        txtCNPJ.setEnabled(false);
        txtRazaoSocial.setEnabled(false);
        jCLogradouro.setEnabled(false);
        jCSocial.setEnabled(false);
        jCTelefone.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(false);

    }
}//Fim Classe Principal

