/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import javax.swing.JOptionPane;
import classes.*;
import enumeradores.*;
import java.awt.Dimension;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistenciaColaborador.ColaboradorDao;

/**
 *
 * @author cabec
 */
public class TelaAtualizarColaborador extends javax.swing.JInternalFrame {

    int acao;

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * Creates new form TelaAtualizarColaborador
     */
    public TelaAtualizarColaborador() {
        initComponents();
        txtCodigo.setEnabled(true);
        txtCodigo.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeDoCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLCPF = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtCELULAR = new javax.swing.JFormattedTextField();
        txtTRABALHO = new javax.swing.JFormattedTextField();
        txtRESIDENCIAL = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCTelefone = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jCLogradouro = new javax.swing.JComboBox<>();
        jlabel = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtEspecialidade = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        txtMensal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();

        setTitle("Atualizar Colaborador");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Colaborador"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 101, -1, -1));

        txtCodigo.setEnabled(false);
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 121, 50, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Nome Colaborador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 101, -1, -1));

        txtNomeDoCliente.setEnabled(false);
        jPanel1.add(txtNomeDoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 121, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Data Nascimento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 101, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("CEP");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 161, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Cidade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 157, -1, -1));

        txtCidade.setEnabled(false);
        jPanel1.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 181, 150, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Estado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 161, -1, -1));

        txtEstado.setEnabled(false);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 183, 200, -1));

        jLCPF.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLCPF.setForeground(new java.awt.Color(242, 242, 242));
        jLCPF.setText("CPF");
        jPanel1.add(jLCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 101, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Endereço De E-mail");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 101, -1, -1));

        txtEmail.setEnabled(false);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 121, 190, -1));

        jButtonSalvar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-save-16 (1).png"))); // NOI18N
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 401, 48, 42));

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setEnabled(false);
        jPanel1.add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 121, 90, -1));

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.setEnabled(false);
        jPanel1.add(txtCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 181, 107, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setEnabled(false);
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 121, 200, -1));

        try {
            txtCELULAR.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCELULAR.setEnabled(false);
        jPanel1.add(txtCELULAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 321, 150, -1));

        try {
            txtTRABALHO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTRABALHO.setEnabled(false);
        jPanel1.add(txtTRABALHO, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 321, 150, -1));

        try {
            txtRESIDENCIAL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRESIDENCIAL.setEnabled(false);
        jPanel1.add(txtRESIDENCIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 321, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 401, 48, 42));

        jButtonEditar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-edit-16 (1).png"))); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 401, 48, 42));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(242, 242, 242));
        jLabel15.setText("Bairro");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 161, -1, -1));

        txtBairro.setEnabled(false);
        jPanel1.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 181, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Numero");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 229, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 242, 242));
        jLabel14.setText("Tipo Logradouro");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 229, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 242, 242));
        jLabel16.setText("Complemento");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 229, -1, -1));

        txtComplemento.setEnabled(false);
        jPanel1.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 249, 200, -1));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(242, 242, 242));
        jLabel18.setText(" Salvar");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 377, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(242, 242, 242));
        jLabel19.setText(" Editar");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 377, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(242, 242, 242));
        jLabel20.setText(" Voltar");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 377, -1, -1));

        jCTelefone.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCTelefone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "RESIDENCIAL", "CELULAR", "TRABALHO" }));
        jCTelefone.setEnabled(false);
        jCTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(jCTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 321, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Telefone");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 299, -1, -1));

        jCLogradouro.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jCLogradouro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "RUA", "AVENIDA" }));
        jCLogradouro.setEnabled(false);
        jCLogradouro.setPreferredSize(new java.awt.Dimension(127, 24));
        jPanel1.add(jCLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 249, 120, 30));

        jlabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(242, 242, 242));
        jlabel.setText("Logradouro");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 229, -1, -1));

        txtLogradouro.setEnabled(false);
        jPanel1.add(txtLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 249, 162, -1));

        txtEspecialidade.setEnabled(false);
        jPanel1.add(txtEspecialidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 321, 200, -1));

        txtHora.setEnabled(false);
        txtHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraFocusLost(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 321, 116, -1));

        txtMensal.setEnabled(false);
        txtMensal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMensalFocusLost(evt);
            }
        });
        jPanel1.add(txtMensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 321, 150, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Especialidade");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 299, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 242, 242));
        jLabel11.setText("Salário Mensal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 299, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("Salário Hora");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 299, -1, -1));

        try {
            txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(621, 249, 150, -1));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        salvar();
        try {
            ColaboradorDao metodos = new ColaboradorDao();
            colaborador adicionarColaborador = new colaborador();
            telefone cadastrarTelefone = new telefone();
            endereco cadastrarEndereco = new endereco();

            if (jCTelefone.getSelectedItem().equals("RESIDENCIAL")) {
                cadastrarTelefone.setTipo(tiposTelefone.RESIDENCIAL);
                cadastrarTelefone.setTelefone(txtRESIDENCIAL.getText());

            } else if (jCTelefone.getSelectedItem().equals("TRABALHO")) {
                cadastrarTelefone.setTipo(tiposTelefone.TRABALHO);
                cadastrarTelefone.setTelefone(txtTRABALHO.getText());

            } else {
                cadastrarTelefone.setTipo(tiposTelefone.CELULAR);
                cadastrarTelefone.setTelefone(txtCELULAR.getText());

            }
            cadastrarEndereco.setBairro(txtBairro.getText());
            cadastrarEndereco.setCep((txtCEP.getText()));
            cadastrarEndereco.setCidade(txtCidade.getText());
            cadastrarEndereco.setComplemento(txtComplemento.getText());
            cadastrarEndereco.setEstado(txtEstado.getText());
            cadastrarEndereco.setLogradouro(txtLogradouro.getText());
            cadastrarEndereco.setNumero(txtNumero.getText());
            if (jCLogradouro.getSelectedItem().equals("RUA")) {
                cadastrarEndereco.setTipo(tipoLogradouro.RUA);
            } else {
                cadastrarEndereco.setTipo(tipoLogradouro.AVENIDA);

            }
            //usando objeto cliente para ler os dados escritos na tela
            adicionarColaborador.setNome(txtNomeDoCliente.getText());
            if (!adicionarColaborador.setCPF(txtCPF.getText())) {
                throw new Exception("CPF Inválido!");
            }
            adicionarColaborador.setDataNascimento(txtDataNascimento.getText());
            adicionarColaborador.setEmail(txtEmail.getText());
            adicionarColaborador.setEndereco(cadastrarEndereco);
            adicionarColaborador.setTelefone(cadastrarTelefone);
            adicionarColaborador.setID(Integer.parseInt(txtCodigo.getText()));
            adicionarColaborador.setEspecialidade(txtEspecialidade.getText());
            adicionarColaborador.setSalarioHora(Float.parseFloat(txtHora.getText()));
            adicionarColaborador.setSalarioMensal(Float.parseFloat(txtMensal.getText()));

            metodos.alterar(adicionarColaborador, Integer.parseInt(txtCodigo.getText()));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }


    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal.cadastro = false;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        acao = 2;
        editar();

        try {
            ColaboradorDao metodos = new ColaboradorDao();
            ArrayList<colaborador> listaColaborador = null;
            listaColaborador = metodos.obterColaborador();
//            for (int i = 0; i < listaColaborador.size(); i++) {
//                if (txtCodigo.getText().equals(String.valueOf(listaColaborador.get(i).getID()))) {
//                    txtNomeDoCliente.setText("" + listaColaborador.get(i).getNome());
//                    jCTelefone.setSelectedItem(String.valueOf(listaColaborador.get(i).getTelefone().getTipo()));
//                    txtCELULAR.setText("" + listaColaborador.get(i).getTelefone().getTelefone());
//                    txtRESIDENCIAL.setText("" + listaColaborador.get(i).getTelefone().getTelefone());
//                    txtTRABALHO.setText("" + listaColaborador.get(i).getTelefone().getTelefone());
//                    txtCPF.setEditable(false);
//                    txtCPF.setText("" + listaColaborador.get(i).getCPF());
//                    txtCEP.setText("" + listaColaborador.get(i).getEndereco().getCep());
//                    txtCidade.setText("" + listaColaborador.get(i).getEndereco().getCidade());
//                    txtComplemento.setText("" + listaColaborador.get(i).getEndereco().getComplemento());
//                    txtDataNascimento.setText(new SimpleDateFormat("dd/MM/yyyy").format(listaColaborador.get(i).getDataNascimento()));
//                    txtEmail.setText("" + listaColaborador.get(i).getEmail());
//                    txtEstado.setText("" + listaColaborador.get(i).getEndereco().getEstado());
//                    txtLogradouro.setText("" + listaColaborador.get(i).getEndereco().getLogradouro());
//                    txtNumero.setText("" + listaColaborador.get(i).getEndereco().getNumero());
//                    txtBairro.setText("" + listaColaborador.get(i).getEndereco().getBairro());
//                    jCLogradouro.setSelectedItem(String.valueOf(listaColaborador.get(i).getEndereco().getTipo()));
//                    txtEspecialidade.setText("" + listaColaborador.get(i).getEspecialidade());
//                    txtHora.setText("" + listaColaborador.get(i).getSalarioHora());
//                    txtMensal.setText("" + listaColaborador.get(i).getSalarioMensal());
//
//                }
//
//            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }


    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jCTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTelefoneActionPerformed
        // TODO add your handling code here:
        if (jCTelefone.getSelectedItem().equals("RESIDENCIAL")) {
            txtCELULAR.setVisible(false);
            txtTRABALHO.setVisible(false);
            txtRESIDENCIAL.setVisible(true);

        } else if (jCTelefone.getSelectedItem().equals("TRABALHO")) {
            txtCELULAR.setVisible(false);
            txtTRABALHO.setVisible(true);
            txtRESIDENCIAL.setVisible(false);

        } else if (jCTelefone.getSelectedItem().equals("CELULAR")) {
            txtCELULAR.setVisible(true);
            txtTRABALHO.setVisible(false);
            txtRESIDENCIAL.setVisible(false);

        }
    }//GEN-LAST:event_jCTelefoneActionPerformed

    private void txtHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFocusLost
        String sv = txtHora.getText();
        String valor = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        BigDecimal v = new BigDecimal(valor);
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorformatado = nf.format(v);
        txtHora.setText(valorformatado);
    }//GEN-LAST:event_txtHoraFocusLost

    private void txtMensalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMensalFocusLost
        String sv = txtMensal.getText();
        String valor = sv.replace("R$", "").replace(" ", "").replace(".", "").replace(",", ".");
        BigDecimal v = new BigDecimal(valor);
        NumberFormat nf = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
        String valorformatado = nf.format(v);
        txtMensal.setText(valorformatado);
    }//GEN-LAST:event_txtMensalFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonEditar;
    public javax.swing.JButton jButtonSalvar;
    public javax.swing.JComboBox<String> jCLogradouro;
    public javax.swing.JComboBox<String> jCTelefone;
    public javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JLabel jLCPF;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlabel;
    public javax.swing.JTextField txtBairro;
    public javax.swing.JFormattedTextField txtCELULAR;
    public javax.swing.JFormattedTextField txtCEP;
    public javax.swing.JFormattedTextField txtCPF;
    public javax.swing.JTextField txtCidade;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtComplemento;
    public javax.swing.JFormattedTextField txtDataNascimento;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtEspecialidade;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtHora;
    public javax.swing.JTextField txtLogradouro;
    public javax.swing.JTextField txtMensal;
    public javax.swing.JTextField txtNomeDoCliente;
    public javax.swing.JFormattedTextField txtNumero;
    public javax.swing.JFormattedTextField txtRESIDENCIAL;
    public javax.swing.JFormattedTextField txtTRABALHO;
    // End of variables declaration//GEN-END:variables
public void novo() {
        txtNomeDoCliente.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtCEP.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEstado.setEnabled(true);
        txtCPF.setEnabled(true);
        txtLogradouro.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCELULAR.setEnabled(true);
        txtRESIDENCIAL.setEnabled(true);
        txtTRABALHO.setEnabled(true);
        txtEmail.setEnabled(true);
        txtNumero.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtNumero.setEnabled(true);
        txtMensal.setEnabled(true);
        txtHora.setEnabled(true);
        txtEspecialidade.setEnabled(true);
        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jCLogradouro.setEnabled(true);
        jCTelefone.setEnabled(true);
        txtNomeDoCliente.setText("");
        txtDataNascimento.setText("");
        txtCEP.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtCPF.setText("");
        txtBairro.setText("");
        txtCELULAR.setText("");
        txtRESIDENCIAL.setText("");
        txtTRABALHO.setText("");
        txtEmail.setText("");
        txtNumero.setText("");
        txtMensal.setText("");
        txtHora.setText("");
        txtEspecialidade.setText("");
        txtComplemento.setText("");
        txtNumero.setText("");
    }

    public void editar() {
        txtNomeDoCliente.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        txtCEP.setEnabled(true);
        txtCidade.setEnabled(true);
        txtEstado.setEnabled(true);
        txtCPF.setEnabled(true);
        txtBairro.setEnabled(true);
        txtCELULAR.setEnabled(true);
        txtRESIDENCIAL.setEnabled(true);
        txtTRABALHO.setEnabled(true);
        txtEmail.setEnabled(true);
        txtNumero.setEnabled(true);
        txtLogradouro.setEnabled(true);
        txtComplemento.setEnabled(true);
        txtNumero.setEnabled(true);
        txtMensal.setEnabled(true);
        txtHora.setEnabled(true);
        txtEspecialidade.setEnabled(true);
        txtCodigo.setEnabled(false);
        jCLogradouro.setEnabled(true);
        jCTelefone.setEnabled(true);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(true);

    }

    public void salvar() {
        txtNomeDoCliente.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        txtCEP.setEnabled(false);
        txtCidade.setEnabled(false);
        txtEstado.setEnabled(false);
        txtCPF.setEnabled(false);
        txtBairro.setEnabled(false);
        txtCELULAR.setEnabled(false);
        txtRESIDENCIAL.setEnabled(false);
        txtTRABALHO.setEnabled(false);
        txtEmail.setEnabled(false);
        txtNumero.setEnabled(false);
        txtMensal.setEnabled(false);
        txtHora.setEnabled(false);
        txtEspecialidade.setEnabled(false);
        txtLogradouro.setEnabled(false);
        txtComplemento.setEnabled(false);
        txtNumero.setEnabled(false);
        txtCodigo.setEnabled(false);
        jCLogradouro.setEnabled(false);
        jCTelefone.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
    }
}//Fim Classe Principal
