/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import classes.veiculo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistenciaVeiculo.veiculoDao;

/**
 *
 * @author cabec
 */
public class TelaConsultaVeiculo extends javax.swing.JInternalFrame {
    public static boolean consultav;
    /**
     * Creates new form TelaConsultaVeiculoo
     */
    public TelaConsultaVeiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jctipodeOpcaoDeBusca = new javax.swing.JComboBox<>();
        jTcampoBusca = new javax.swing.JTextField();
        jPlaca = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();
        JtableSaida = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jButtonexcluir = new javax.swing.JButton();

        setTitle("Consulta Veículo");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jctipodeOpcaoDeBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "ID Cliente", "Placa" }));
        jctipodeOpcaoDeBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jctipodeOpcaoDeBuscaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 6, 0, 0);
        jPanel1.add(jctipodeOpcaoDeBusca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 0);
        jPanel1.add(jTcampoBusca, gridBagConstraints);

        try {
            jPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPlaca.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 18, 0, 0);
        jPanel1.add(jPlaca, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Excluir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 44, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 33, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  Voltar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 77, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jButtonBuscar.setBackground(new java.awt.Color(51, 255, 0));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 27, 0, 0);
        jPanel1.add(jButtonBuscar, gridBagConstraints);

        JtableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Modelo ", "Marca", "ID", "ID Cliente", "Ano Do Modelo", "Ano Fabricação", "Placa", "Renavam", "Tipo Veículo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JtableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableSaidaMouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(JtableSaida);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 909;
        gridBagConstraints.ipady = 374;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 0, 0);
        jPanel1.add(jScrollPane, gridBagConstraints);

        jButtonVoltar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-16.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 77, 0, 0);
        jPanel1.add(jButtonVoltar, gridBagConstraints);

        jButtonexcluir.setBackground(new java.awt.Color(255, 51, 0));
        jButtonexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-trash-16.png"))); // NOI18N
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 39, 0, 0);
        jPanel1.add(jButtonexcluir, gridBagConstraints);

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jctipodeOpcaoDeBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jctipodeOpcaoDeBuscaActionPerformed
        if (jctipodeOpcaoDeBusca.getSelectedItem().equals("ID")) {
            jTcampoBusca.setVisible(true);
            jTcampoBusca.setEnabled(true);
            jPlaca.setVisible(false);
            jPlaca.setEnabled(false);
        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("ID Cliente")) {
            jTcampoBusca.setVisible(true);
            jTcampoBusca.setEnabled(true);
            jPlaca.setVisible(false);
            jPlaca.setEnabled(false);

        } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Placa")) {
            jTcampoBusca.setVisible(false);
            jTcampoBusca.setEnabled(false);
            jPlaca.setVisible(true);
            jPlaca.setEnabled(true);
        }
    }//GEN-LAST:event_jctipodeOpcaoDeBuscaActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            veiculoDao metodos = new veiculoDao();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            ArrayList<veiculo> listaVeiculo = null;
            listaVeiculo = metodos.obterVeiculo();
            String[] vetString = new String[9];
            model.setRowCount(0);
            boolean contem = false;
            for (int i = 0; i < listaVeiculo.size(); i++) {
                vetString[0] = listaVeiculo.get(i).getModeloVeiculo().getDescricao() + "";
                vetString[1] = listaVeiculo.get(i).getMarcaVeiculo().getDescricao() + "";
                vetString[2] = listaVeiculo.get(i).getID() + "";
                vetString[3] = listaVeiculo.get(i).getIdCliente() + "";
                vetString[4] = listaVeiculo.get(i).getModeloVeiculo().getAnoModelo() + "";
                vetString[5] = listaVeiculo.get(i).getModeloVeiculo().getAnoFabricacao() + "";
                vetString[6] = listaVeiculo.get(i).getPlaca() + "";
                vetString[7] = listaVeiculo.get(i).getRenavam() + "";
                vetString[8] = listaVeiculo.get(i).getTipo() + "";
                if (jctipodeOpcaoDeBusca.getSelectedItem().equals("ID")) {
                    if (String.valueOf(listaVeiculo.get(i).getID()).contains(jTcampoBusca.getText())) {
                        model.addRow(vetString);
                        contem = true;

                    }

                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("ID Cliente")) {
                    if (String.valueOf(listaVeiculo.get(i).getIdCliente()).contains(jTcampoBusca.getText())) {
                        model.addRow(vetString);
                        contem = true;
                    }
                } else if (jctipodeOpcaoDeBusca.getSelectedItem().equals("Placa")) {
                    if (listaVeiculo.get(i).getPlaca().toUpperCase().contains(jTcampoBusca.getText().toUpperCase())) {
                        model.addRow(vetString);
                        contem = true;
                    }

                }
            }
            if (contem == false) {
                throw new Exception("Veiculo não encontrado");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
            erro.printStackTrace();
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void JtableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableSaidaMouseClicked
        try {

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_JtableSaidaMouseClicked

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
        TelaPrincipal.consultav = false;
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        try {
            veiculoDao metodos = new veiculoDao();
            ArrayList<veiculo> listaVeiculo = null;
            listaVeiculo = metodos.obterVeiculo();
            DefaultTableModel model = (DefaultTableModel) JtableSaida.getModel();
            String[] vetString = new String[9];
            String usuario = "" + JtableSaida.getValueAt(JtableSaida.getSelectedRow(), 2);
            for (int i = 0; i < listaVeiculo.size(); i++) {
                if (String.valueOf(listaVeiculo.get(i).getID()).equals(usuario)) {
                    metodos.excluir(listaVeiculo.get(i).getID());
                }

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
    }//GEN-LAST:event_jButtonexcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableSaida;
    private javax.swing.JToggleButton jButtonBuscar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jPlaca;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTcampoBusca;
    private javax.swing.JComboBox<String> jctipodeOpcaoDeBusca;
    // End of variables declaration//GEN-END:variables
}
