/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Tela;

import classes.OS;
import classes.cliente;
import classes.colaborador;
import enumeradores.statusOS;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalButtonUI;
import javax.swing.table.DefaultTableModel;
import persistenciaCliente.ClienteDao;
import persistenciaColaborador.ColaboradorDao;
import persistenciaOS.OsDao;

/**
 *
 * @author cabec
 */
public class TelaAtualizarOrçamento extends javax.swing.JInternalFrame {

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public TelaAtualizarOrçamento() {
        initComponents();
        //
        try {
            ColaboradorDao metodos = new ColaboradorDao();
            ArrayList<colaborador> listaColaborador = null;
            listaColaborador = metodos.obterColaborador();

            DefaultComboBoxModel modelColaborador = (DefaultComboBoxModel) jComboBox2.getModel();
            String[] vetString = new String[listaColaborador.size()];
            for (int i = 0; i < listaColaborador.size(); i++) {

                vetString[i] = listaColaborador.get(i).getNome();

            }
            jComboBox2.setModel(new DefaultComboBoxModel(vetString));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }

        jEscolherTipoBuscaCliente.setVisible(false);
        txtBuscarClienteO.setVisible(false);
        jBuscarPor.setVisible(false);
        jButtonBuscarO.setVisible(false);
        txtCPFO.setVisible(false);
        txtCNPJO.setVisible(false);
        //peca///////////////////////////////////
        jEscolherTipoBuscaPeca.setVisible(false);
        jButtonBuscarPeca.setVisible(false);
        txtBuscarPecasO.setVisible(false);
        //servico/////////////////////////////
        txtBuscarServico.setVisible(false);
        jButtonBuscarServico.setVisible(false);
        jEscolherTipoBuscaServico.setVisible(false);
        //veiculo/////////////////////////////

        jEscolherTipoBuscaVeiculo.setVisible(false);
        txtBuscarVeiculo.setVisible(false);
        txtBuscarVeiculo.setEnabled(false);
        txtPlaca.setVisible(false);
        txtPlaca.setEnabled(false);
        //campos CNPJOS-CPFOS//
        txtCPFOS.setVisible(false);
        txtCPFOS.setVisible(false);
        txtCNPJOS.setVisible(false);
        jCNPJOS.setVisible(false);
        jCPFOS.setVisible(false);
        //
        //Botoes//
        jButtonAprovarOrçamento.setBounds(0, 0, 100, 30);
        jButtonAprovarOrçamento.setOpaque(false);
        jButtonAprovarOrçamento.setContentAreaFilled(false);
        jButtonAprovarOrçamento.setBorderPainted(true);
        jButtonVoltarO.setBounds(0, 0, 100, 30);
        jButtonVoltarO.setOpaque(false);
        jButtonVoltarO.setContentAreaFilled(false);
        jButtonVoltarO.setBorderPainted(true);
        jButtonCancelarOS.setBounds(0, 0, 100, 30);
        jButtonCancelarOS.setOpaque(false);
        jButtonCancelarOS.setContentAreaFilled(false);
        jButtonCancelarOS.setBorderPainted(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTelaAtualizarOrçamento = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jCEscolherLista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        txtBuscarClienteO = new javax.swing.JTextField();
        jButtonBuscarO = new javax.swing.JToggleButton();
        txtBuscarPecasO = new javax.swing.JTextField();
        jBuscarPor = new javax.swing.JLabel();
        jEscolherTipoBuscaCliente = new javax.swing.JComboBox<>();
        txtCPFO = new javax.swing.JFormattedTextField();
        txtCNPJO = new javax.swing.JFormattedTextField();
        jEscolherTipoBuscaPeca = new javax.swing.JComboBox<>();
        jButtonBuscarPeca = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtIDcliente = new javax.swing.JTextField();
        jTipoPessoaOS = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jCNPJOS = new javax.swing.JLabel();
        jCPFOS = new javax.swing.JLabel();
        txtCPFOS = new javax.swing.JFormattedTextField();
        txtCNPJOS = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDVeiculo = new javax.swing.JTextField();
        txctgdf = new javax.swing.JLabel();
        txtModeloVeiculo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPLACA = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIDservico = new javax.swing.JTextField();
        txtDescricaoServico = new javax.swing.JTextField();
        txtValorServico = new javax.swing.JTextField();
        txtTipoServico = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtIDpeca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDescricaoPeca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtValorPeca = new javax.swing.JTextField();
        txtBuscarServico = new javax.swing.JTextField();
        jButtonBuscarServico = new javax.swing.JToggleButton();
        jEscolherTipoBuscaServico = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtIDos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonAprovarOrçamento = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButtonVoltarO = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProblemaRelatado = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jValorTotal = new javax.swing.JTextField();
        jButtonCancelarOS = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JFormattedTextField();
        txtBuscarVeiculo = new javax.swing.JTextField();
        jEscolherTipoBuscaVeiculo = new javax.swing.JComboBox<>();
        jButtonBuscarVeiculo = new javax.swing.JToggleButton();

        setTitle("Atualizar Orçamento");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCEscolherLista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Cliente", "Peça", "Serviço" }));
        jCEscolherLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCEscolherListaActionPerformed(evt);
            }
        });
        jPanel1.add(jCEscolherLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 531, -1, -1));

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID", "CPF/CNPJ", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCliente.setEnabled(false);
        jScrollPane1.setViewportView(jTableCliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 531, 910, 146));
        jPanel1.add(txtBuscarClienteO, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));

        jButtonBuscarO.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBuscarO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscarO.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarOActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 601, 30, 22));
        jPanel1.add(txtBuscarPecasO, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));

        jBuscarPor.setBackground(new java.awt.Color(255, 255, 255));
        jBuscarPor.setForeground(new java.awt.Color(255, 255, 255));
        jBuscarPor.setText("Buscar Por");
        jPanel1.add(jBuscarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 571, -1, -1));

        jEscolherTipoBuscaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Nome", "CPF", "CNPJ" }));
        jEscolherTipoBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolherTipoBuscaClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jEscolherTipoBuscaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 571, -1, -1));

        try {
            txtCPFO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCPFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));

        try {
            txtCNPJO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCNPJO, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));

        jEscolherTipoBuscaPeca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "ID", "Descrição" }));
        jEscolherTipoBuscaPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolherTipoBuscaPecaActionPerformed(evt);
            }
        });
        jPanel1.add(jEscolherTipoBuscaPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 571, -1, -1));

        jButtonBuscarPeca.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBuscarPeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscarPeca.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jButtonBuscarPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 601, 30, 22));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 18, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ID");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, -1, -1));
        jPanel2.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 140, -1));
        jPanel2.add(txtIDcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 60, -1));

        jTipoPessoaOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "PESSOAFISICA", "PESSOAJURIDICA" }));
        jTipoPessoaOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoPessoaOSActionPerformed(evt);
            }
        });
        jPanel2.add(jTipoPessoaOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 40, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo De Pessoa");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 18, -1, -1));

        jCNPJOS.setForeground(new java.awt.Color(255, 255, 255));
        jCNPJOS.setText("CNPJ");
        jPanel2.add(jCNPJOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 18, -1, -1));

        jCPFOS.setForeground(new java.awt.Color(242, 242, 242));
        jCPFOS.setText("CPF");
        jPanel2.add(jCPFOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 18, -1, -1));

        try {
            txtCPFOS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCPFOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, -1));

        try {
            txtCNPJOS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCNPJOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Modelo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, -1, -1));
        jPanel2.add(txtIDVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 120, -1));

        txctgdf.setForeground(new java.awt.Color(0, 0, 255));
        txctgdf.setText("ID Veiculo");
        jPanel2.add(txctgdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));
        jPanel2.add(txtModeloVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 120, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Placa");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, -1));
        jPanel2.add(txtPLACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 171, 1140, 90));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Serviço\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 0, 255));
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("ID");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));

        jLabel12.setForeground(new java.awt.Color(242, 242, 242));
        jLabel12.setText("Tipo Serviço");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 24, -1, -1));

        jLabel13.setForeground(new java.awt.Color(242, 242, 242));
        jLabel13.setText("Descrição");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 98, -1, -1));

        jLabel14.setForeground(new java.awt.Color(242, 242, 242));
        jLabel14.setText("Valor");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 98, -1, -1));
        jPanel3.add(txtIDservico, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, 40, -1));
        jPanel3.add(txtDescricaoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 120, 130, -1));
        jPanel3.add(txtValorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 120, 80, -1));
        jPanel3.add(txtTipoServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 281, 320, 180));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Peça", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("ID");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));
        jPanel4.add(txtIDpeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, 40, -1));

        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Descrição");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 95, -1, -1));
        jPanel4.add(txtDescricaoPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 117, 130, -1));

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Qnt.");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 24, -1, -1));
        jPanel4.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 46, 80, -1));

        jLabel10.setForeground(new java.awt.Color(242, 242, 242));
        jLabel10.setText("Valor/U");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 95, -1, -1));
        jPanel4.add(txtValorPeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 117, 80, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 281, 340, 180));
        jPanel1.add(txtBuscarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));

        jButtonBuscarServico.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBuscarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscarServico.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jButtonBuscarServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 601, 30, 22));

        jEscolherTipoBuscaServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "ID", "Tipo Serviço", "Descrição" }));
        jEscolherTipoBuscaServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolherTipoBuscaServicoActionPerformed(evt);
            }
        });
        jPanel1.add(jEscolherTipoBuscaServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 571, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Código Da OS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 51, -1, -1));
        jPanel1.add(txtIDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 51, 60, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Emissão");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 91, -1, -1));

        jButtonAprovarOrçamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-create-64.png"))); // NOI18N
        jButtonAprovarOrçamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAprovarOrçamentoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAprovarOrçamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 71, -1, -1));

        jLabel15.setForeground(new java.awt.Color(242, 242, 242));
        jLabel15.setText("Aprovar Orçamento");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jButtonVoltarO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-return-64 (1).png"))); // NOI18N
        jButtonVoltarO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarOActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltarO, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 71, -1, -1));

        jLabel16.setForeground(new java.awt.Color(242, 242, 242));
        jLabel16.setText("Retornar");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 141, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/c4b6d88c-a30e-4ebd-b7dd-8287cfc3937e-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 130, -1));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Funcionario Responsavel");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 131, -1, -1));

        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 131, 160, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Problema Relatado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        txtProblemaRelatado.setColumns(20);
        txtProblemaRelatado.setRows(5);
        jScrollPane2.setViewportView(txtProblemaRelatado);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 281, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Valor Total :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel20))
                .addGap(9, 9, 9))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 481, -1, 40));

        jButtonCancelarOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-subscription-64.png"))); // NOI18N
        jButtonCancelarOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarOSActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelarOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 71, -1, -1));

        jLabel21.setForeground(new java.awt.Color(242, 242, 242));
        jLabel21.setText("Cancelar Orçamento");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));
        jPanel1.add(txtBuscarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 601, 150, -1));

        jEscolherTipoBuscaVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jEscolherTipoBuscaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEscolherTipoBuscaVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(jEscolherTipoBuscaVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1017, 571, -1, -1));

        jButtonBuscarVeiculo.setBackground(new java.awt.Color(153, 153, 153));
        jButtonBuscarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icones/icons8-magnifying-glass-16 (1).png"))); // NOI18N
        jButtonBuscarVeiculo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonBuscarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1107, 601, 30, 22));

        jTelaAtualizarOrçamento.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jTelaAtualizarOrçamentoLayout = new javax.swing.GroupLayout(jTelaAtualizarOrçamento);
        jTelaAtualizarOrçamento.setLayout(jTelaAtualizarOrçamentoLayout);
        jTelaAtualizarOrçamentoLayout.setHorizontalGroup(
            jTelaAtualizarOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jTelaAtualizarOrçamentoLayout.setVerticalGroup(
            jTelaAtualizarOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaAtualizarOrçamento)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTelaAtualizarOrçamento)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCEscolherListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCEscolherListaActionPerformed
        if (jCEscolherLista.getSelectedItem().equals("Selecione...")) {
            jEscolherTipoBuscaCliente.setVisible(false);
            jEscolherTipoBuscaCliente.setEnabled(false);
            jEscolherTipoBuscaPeca.setEnabled(false);
            jEscolherTipoBuscaPeca.setVisible(false);
            jEscolherTipoBuscaServico.setEnabled(false);
            jEscolherTipoBuscaServico.setVisible(false);
            jBuscarPor.setVisible(false);
            jButtonBuscarO.setVisible(false);

            //cliente
            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);
            //peça
            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            jButtonBuscarPeca.setVisible(false);
            //servico/////////////////////////////
            txtBuscarServico.setVisible(false);
            txtBuscarServico.setEnabled(false);

            jButtonBuscarServico.setVisible(false);
            //veiculo
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarVeiculo.setVisible(false);

        }
        if (jCEscolherLista.getSelectedItem().equals("Cliente")) {
            jTableCliente.setModel(new DefaultTableModel(new Object[]{"ID", "Nome", "Modelo", "CPF/CNPJ"}, 0));
            //combo box
            jEscolherTipoBuscaCliente.setVisible(true);
            jEscolherTipoBuscaCliente.setEnabled(true);
            jBuscarPor.setVisible(true);
            jEscolherTipoBuscaCliente.setSelectedIndex(0);
            //cliente////////////////////////////////
            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jButtonBuscarO.setVisible(false);
            //peça/////////////////////////////////
            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            jButtonBuscarPeca.setVisible(false);

            jEscolherTipoBuscaPeca.setVisible(false);
            jEscolherTipoBuscaPeca.setEnabled(false);
            //servico/////////////////////////////
            txtBuscarServico.setVisible(false);
            txtBuscarServico.setEnabled(false);

            jButtonBuscarServico.setVisible(false);

            jEscolherTipoBuscaServico.setVisible(false);
            jEscolherTipoBuscaServico.setEnabled(false);
            //veiculo
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarVeiculo.setVisible(false);
        }
        if (jCEscolherLista.getSelectedItem().equals("Peça")) {
            jTableCliente.setModel(new DefaultTableModel(new Object[]{"ID", "Descrição", "Valor/U", "Qnt.Estoque"}, 0));
            jEscolherTipoBuscaCliente.setVisible(false);
            jEscolherTipoBuscaCliente.setEnabled(false);
            jButtonBuscarO.setVisible(false);
            jEscolherTipoBuscaPeca.setSelectedIndex(0);
            //cliente////////////////////////////////
            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jEscolherTipoBuscaCliente.setVisible(false);
            jEscolherTipoBuscaCliente.setEnabled(false);
            //peça/////////////////////////////////
            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            jButtonBuscarPeca.setVisible(false);
            //servico/////////////////////////////
            txtBuscarServico.setVisible(false);
            txtBuscarServico.setEnabled(false);

            jButtonBuscarServico.setVisible(false);

            jEscolherTipoBuscaServico.setVisible(false);
            jEscolherTipoBuscaServico.setEnabled(false);
            //combo box
            jEscolherTipoBuscaPeca.setVisible(true);
            jEscolherTipoBuscaPeca.setEnabled(true);
            //label
            jBuscarPor.setVisible(true);
            //veiculo
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarVeiculo.setVisible(false);
        }
        if (jCEscolherLista.getSelectedItem().equals("Serviço")) {
            jTableCliente.setModel(new DefaultTableModel(new Object[]{"ID", "Tipo De Serviço", "Descrição", "Valor"}, 0));
            jEscolherTipoBuscaServico.setVisible(true);
            jEscolherTipoBuscaServico.setEnabled(true);
            jBuscarPor.setVisible(true);
            jEscolherTipoBuscaServico.setSelectedIndex(0);
            //cliente
            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jEscolherTipoBuscaCliente.setVisible(false);
            jEscolherTipoBuscaCliente.setEnabled(false);
            //peça
            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            jButtonBuscarPeca.setVisible(false);

            jEscolherTipoBuscaPeca.setVisible(false);
            jEscolherTipoBuscaPeca.setEnabled(false);

            //servico/////////////////////////////
            txtBuscarServico.setVisible(false);
            txtBuscarServico.setEnabled(false);

            jButtonBuscarServico.setVisible(false);
            //veiculo
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarVeiculo.setVisible(false);
        }
        if (jCEscolherLista.getSelectedItem().equals("Veiculo")) {
            jTableCliente.setModel(new DefaultTableModel(new Object[]{"ID", "Modelo", "Placa", "Ano"}, 0));
            jEscolherTipoBuscaVeiculo.setVisible(true);
            jEscolherTipoBuscaVeiculo.setEnabled(true);
            jBuscarPor.setVisible(true);
            jEscolherTipoBuscaVeiculo.setSelectedIndex(0);
            //cliente
            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jEscolherTipoBuscaCliente.setVisible(false);
            jEscolherTipoBuscaCliente.setEnabled(false);
            //peça
            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            jButtonBuscarPeca.setVisible(false);

            jEscolherTipoBuscaPeca.setVisible(false);
            jEscolherTipoBuscaPeca.setEnabled(false);

            //servico/////////////////////////////
            txtBuscarServico.setVisible(false);
            txtBuscarServico.setEnabled(false);

            jButtonBuscarServico.setVisible(false);
            //veiculo
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarVeiculo.setVisible(false);
        }
    }//GEN-LAST:event_jCEscolherListaActionPerformed

    private void jButtonBuscarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarOActionPerformed

    }//GEN-LAST:event_jButtonBuscarOActionPerformed

    private void jEscolherTipoBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolherTipoBuscaClienteActionPerformed
        if (jEscolherTipoBuscaCliente.getSelectedItem().equals("Selecione...")) {
            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jButtonBuscarO.setVisible(false);
            jEscolherTipoBuscaPeca.setVisible(false);
            jButtonBuscarPeca.setVisible(false);
        }
        if (jEscolherTipoBuscaCliente.getSelectedItem().equals("CNPJ")) {
            txtCNPJO.setVisible(true);
            txtCNPJO.setEnabled(true);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jButtonBuscarO.setVisible(true);
            jEscolherTipoBuscaPeca.setVisible(false);
        }
        if (jEscolherTipoBuscaCliente.getSelectedItem().equals("CPF")) {

            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(true);
            txtCPFO.setVisible(true);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(false);
            txtBuscarClienteO.setEnabled(false);

            jButtonBuscarO.setVisible(true);
            jEscolherTipoBuscaPeca.setVisible(false);
        }
        if (jEscolherTipoBuscaCliente.getSelectedItem().equals("Nome")) {

            txtCNPJO.setVisible(false);
            txtCNPJO.setEnabled(false);

            txtCPFO.setEnabled(false);
            txtCPFO.setVisible(false);

            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            txtBuscarClienteO.setVisible(true);
            txtBuscarClienteO.setEnabled(true);

            jButtonBuscarO.setVisible(true);
            jEscolherTipoBuscaPeca.setVisible(false);
    }//GEN-LAST:event_jEscolherTipoBuscaClienteActionPerformed
    }
    private void jEscolherTipoBuscaPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolherTipoBuscaPecaActionPerformed
        if (jEscolherTipoBuscaPeca.getSelectedItem().equals("Selecione...")) {
            txtBuscarPecasO.setVisible(false);
            txtBuscarPecasO.setEnabled(false);

            jButtonBuscarPeca.setVisible(false);
        }
        if (jEscolherTipoBuscaPeca.getSelectedItem().equals("ID")) {
            txtBuscarPecasO.setVisible(true);
            txtBuscarPecasO.setEnabled(true);

            jButtonBuscarPeca.setVisible(true);
        }
        if (jEscolherTipoBuscaPeca.getSelectedItem().equals("Descrição")) {
            txtBuscarPecasO.setVisible(true);
            txtBuscarPecasO.setEnabled(true);

            jButtonBuscarPeca.setVisible(true);

        }
    }//GEN-LAST:event_jEscolherTipoBuscaPecaActionPerformed

    private void jTipoPessoaOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoPessoaOSActionPerformed
        if (jTipoPessoaOS.getSelectedItem().equals("PESSOAFISICA")) {

            txtCPFOS.setEnabled(true);
            txtCPFOS.setVisible(true);
            jCPFOS.setVisible(true);
            txtCNPJOS.setVisible(false);
            jCNPJOS.setVisible(false);

        } else if (jTipoPessoaOS.getSelectedItem().equals("PESSOAJURIDICA")) {

            txtCPFOS.setVisible(false);
            jCPFOS.setVisible(false);
            txtCNPJOS.setVisible(true);
            jCNPJOS.setVisible(true);
        } else if (jTipoPessoaOS.getSelectedItem().equals("Selecione...")) {

            txtCPFOS.setVisible(false);
            txtCPFOS.setVisible(false);
            txtCNPJOS.setVisible(false);
            jCNPJOS.setVisible(false);
            jCPFOS.setVisible(false);
        }
    }//GEN-LAST:event_jTipoPessoaOSActionPerformed

    private void jEscolherTipoBuscaServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolherTipoBuscaServicoActionPerformed
        if (jEscolherTipoBuscaServico.getSelectedItem().equals("Selecione...")) {
            txtBuscarServico.setVisible(false);
            txtBuscarServico.setEnabled(false);

            jButtonBuscarServico.setVisible(false);
        }
        if (jEscolherTipoBuscaServico.getSelectedItem().equals("ID")) {
            txtBuscarServico.setVisible(true);
            txtBuscarServico.setEnabled(true);

            jButtonBuscarServico.setVisible(true);
        }
        if (jEscolherTipoBuscaServico.getSelectedItem().equals("Tipo Serviço")) {
            txtBuscarServico.setVisible(true);
            txtBuscarServico.setEnabled(true);

            jButtonBuscarServico.setVisible(true);
        }
        if (jEscolherTipoBuscaServico.getSelectedItem().equals("Descrição")) {
            txtBuscarServico.setVisible(true);
            txtBuscarServico.setEnabled(true);

            jButtonBuscarServico.setVisible(true);
        }
    }//GEN-LAST:event_jEscolherTipoBuscaServicoActionPerformed

    private void jButtonAprovarOrçamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAprovarOrçamentoActionPerformed
        try {
            OsDao metodos = new OsDao();
            OS alterar = new OS();
            ArrayList<OS> listaOS = null;
            listaOS = metodos.obterOS();

            for (int i = 0; i < listaOS.size(); i++) {
                if (String.valueOf(listaOS.get(i).getCodigoDaOs()).equals(txtIDos.getText())) {
                    alterar.setCodigoDaOs(listaOS.get(i).getCodigoDaOs());
                    alterar.setIdCliente(listaOS.get(i).getIdCliente());
                    alterar.setIdPeca(listaOS.get(i).getIdPeca());
                    alterar.setIdServico(listaOS.get(i).getIdServico());
                    alterar.setIdVeiculo(listaOS.get(i).getIdVeiculo());
                    alterar.setIdfuncioanrioResponsavel(listaOS.get(i).getIdfuncioanrioResponsavel());
                    alterar.setQuantidadePecas(Integer.parseInt(txtQuantidade.getText()));
                    alterar.setValorMaoDeobra(listaOS.get(i).getValorMaoDeobra());
                    alterar.setValorUnitarioPecas(listaOS.get(i).getValorUnitarioPecas());
                    alterar.setStatus(statusOS.FINALIZADA);

                }

            }
            metodos.alterar(alterar, Integer.parseInt(txtIDos.getText()));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        dispose();

    }//GEN-LAST:event_jButtonAprovarOrçamentoActionPerformed

    private void jButtonVoltarOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarOActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarOActionPerformed

    private void jButtonCancelarOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarOSActionPerformed

        try {
            OsDao metodos = new OsDao();
            OS alterar = new OS();
            ArrayList<OS> listaOS = null;
            listaOS = metodos.obterOS();

            for (int i = 0; i < listaOS.size(); i++) {
                if (String.valueOf(listaOS.get(i).getCodigoDaOs()).equals(txtIDos.getText())) {
                    alterar.setCodigoDaOs(listaOS.get(i).getCodigoDaOs());
                    alterar.setIdCliente(listaOS.get(i).getIdCliente());
                    alterar.setIdPeca(listaOS.get(i).getIdPeca());
                    alterar.setIdServico(listaOS.get(i).getIdServico());
                    alterar.setIdVeiculo(listaOS.get(i).getIdVeiculo());
                    alterar.setIdfuncioanrioResponsavel(listaOS.get(i).getIdfuncioanrioResponsavel());
                    alterar.setQuantidadePecas(Integer.parseInt(txtQuantidade.getText()));
                    alterar.setValorMaoDeobra(listaOS.get(i).getValorMaoDeobra());
                    alterar.setValorUnitarioPecas(listaOS.get(i).getValorUnitarioPecas());
                    alterar.setStatus(statusOS.CANCELADA);

                }

            }
            metodos.alterar(alterar, Integer.parseInt(txtIDos.getText()));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, erro);
        }
        dispose();
    }//GEN-LAST:event_jButtonCancelarOSActionPerformed

    private void jButtonBuscarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarVeiculoActionPerformed

    private void jEscolherTipoBuscaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEscolherTipoBuscaVeiculoActionPerformed
        if (jEscolherTipoBuscaVeiculo.getSelectedItem().equals("Selecione...")) {
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarServico.setVisible(false);
        }
        if (jEscolherTipoBuscaVeiculo.getSelectedItem().equals("ID Cliente")) {
            txtBuscarVeiculo.setVisible(true);
            txtBuscarVeiculo.setEnabled(true);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarServico.setVisible(true);
        }
        if (jEscolherTipoBuscaVeiculo.getSelectedItem().equals("Modelo")) {
            txtBuscarVeiculo.setVisible(true);
            txtBuscarVeiculo.setEnabled(true);
            txtPlaca.setVisible(false);
            txtPlaca.setEnabled(false);

            jButtonBuscarServico.setVisible(true);
        }
        if (jEscolherTipoBuscaVeiculo.getSelectedItem().equals("Placa")) {
            txtBuscarVeiculo.setVisible(false);
            txtBuscarVeiculo.setEnabled(false);
            txtPlaca.setVisible(true);
            txtPlaca.setEnabled(true);

            jButtonBuscarServico.setVisible(true);
        }
    }//GEN-LAST:event_jEscolherTipoBuscaVeiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jBuscarPor;
    public javax.swing.JButton jButtonAprovarOrçamento;
    public javax.swing.JToggleButton jButtonBuscarO;
    public javax.swing.JToggleButton jButtonBuscarPeca;
    public javax.swing.JToggleButton jButtonBuscarServico;
    public javax.swing.JToggleButton jButtonBuscarVeiculo;
    public javax.swing.JButton jButtonCancelarOS;
    public javax.swing.JButton jButtonVoltarO;
    public javax.swing.JComboBox<String> jCEscolherLista;
    public javax.swing.JLabel jCNPJOS;
    public javax.swing.JLabel jCPFOS;
    public javax.swing.JComboBox<String> jComboBox2;
    public javax.swing.JComboBox<String> jEscolherTipoBuscaCliente;
    public javax.swing.JComboBox<String> jEscolherTipoBuscaPeca;
    public javax.swing.JComboBox<String> jEscolherTipoBuscaServico;
    public javax.swing.JComboBox<String> jEscolherTipoBuscaVeiculo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTableCliente;
    public javax.swing.JDesktopPane jTelaAtualizarOrçamento;
    public javax.swing.JComboBox<String> jTipoPessoaOS;
    public javax.swing.JTextField jValorTotal;
    public javax.swing.JLabel txctgdf;
    public javax.swing.JTextField txtBuscarClienteO;
    public javax.swing.JTextField txtBuscarPecasO;
    public javax.swing.JTextField txtBuscarServico;
    public javax.swing.JTextField txtBuscarVeiculo;
    public javax.swing.JFormattedTextField txtCNPJO;
    public javax.swing.JFormattedTextField txtCNPJOS;
    public javax.swing.JFormattedTextField txtCPFO;
    public javax.swing.JFormattedTextField txtCPFOS;
    public javax.swing.JTextField txtDescricaoPeca;
    public javax.swing.JTextField txtDescricaoServico;
    public javax.swing.JTextField txtIDVeiculo;
    public javax.swing.JTextField txtIDcliente;
    public javax.swing.JTextField txtIDos;
    public javax.swing.JTextField txtIDpeca;
    public javax.swing.JTextField txtIDservico;
    public javax.swing.JTextField txtModeloVeiculo;
    public javax.swing.JTextField txtNomeCliente;
    public javax.swing.JTextField txtPLACA;
    public javax.swing.JFormattedTextField txtPlaca;
    public javax.swing.JTextArea txtProblemaRelatado;
    public javax.swing.JTextField txtQuantidade;
    public javax.swing.JTextField txtTipoServico;
    public javax.swing.JTextField txtValorPeca;
    public javax.swing.JTextField txtValorServico;
    // End of variables declaration//GEN-END:variables
}
